# NumPy 고급 연습 문제

이 노트북은 NumPy의 고급 기능들을 다루는 종합적인 연습 문제들을 포함합니다.

## 학습 목표
- 통계 함수 활용
- 정렬 및 검색 알고리즘
- 배열 조작 및 변형
- 실무 데이터 분석 시나리오


In [1]:
import numpy as np
import matplotlib.pyplot as plt

## 문제 1: 학생 성적 데이터 분석

다음은 5명의 학생이 3과목(수학, 영어, 과학)에서 받은 점수입니다.

```python
scores = np.array([[85, 92, 78],
                   [90, 88, 95],
                   [76, 85, 82],
                   [88, 91, 87],
                   [92, 89, 94]])
```

다음 작업을 수행하세요:
1. 각 학생의 평균 점수를 구하세요
2. 각 과목의 평균 점수를 구하세요
3. 전체 평균 점수를 구하세요
4. 90점 이상을 받은 학생의 수를 구하세요
5. 각 과목에서 가장 높은 점수를 받은 학생의 인덱스를 구하세요


In [14]:
scores = np.array([[85, 92, 78],
                   [90, 88, 95],
                   [76, 85, 82],
                   [88, 91, 87],
                   [92, 89, 94]])
student_avg = np.mean(scores, axis=1)
print(f"각 학생의 평균 점수:{student_avg}")
print("\n" + "="*50)
subject_avg = np.mean(scores, axis=0)
print(f"각 과목의 평균 점수 :{subject_avg}")
total_avg = np.mean(scores)
print(f"전체 평균 점수 : {total_avg:.2f}")
high_scores = np.sum(scores >= 90)
print(f"90점 이상 맞은 학생 수: {high_scores}")
max_student_indices = np.argmax(scores, axis=0)
print(f"각 과목 최고점 학생 인덱스: {max_student_indices}")

각 학생의 평균 점수:[85.         91.         81.         88.66666667 91.66666667]

각 과목의 평균 점수 :[86.2 89.  87.2]
전체 평균 점수 : 87.47
90점 이상 맞은 학생 수: 6
각 과목 최고점 학생 인덱스: [4 0 1]


In [ ]:
# 여기에 코드를 작성하세요
scores = np.array([[85, 92, 78],
                   [90, 88, 95],
                   [76, 85, 82],
                   [88, 91, 87],
                   [92, 89, 94]])

print("학생 성적 데이터:")
print(scores)
print("\n" + "="*50)

# 1. 각 학생의 평균 점수
student_avg = np.mean(scores, axis=1)
print(f"각 학생의 평균 점수: {student_avg}")

# 2. 각 과목의 평균 점수
subject_avg = np.mean(scores, axis=0)
print(f"각 과목의 평균 점수: {subject_avg}")

# 3. 전체 평균 점수
total_avg = np.mean(scores)
print(f"전체 평균 점수: {total_avg:.2f}")

# 4. 90점 이상을 받은 학생의 수
high_scores = np.sum(scores >= 90)
print(f"90점 이상을 받은 횟수: {high_scores}회")

# 5. 각 과목에서 가장 높은 점수를 받은 학생의 인덱스
max_student_indices = np.argmax(scores, axis=0)
print(f"각 과목 최고점 학생 인덱스: {max_student_indices}")


## 문제 2: 주식 가격 데이터 분석

다음은 10일간의 주식 가격 데이터입니다.

```python
stock_prices = np.array([100, 102, 98, 105, 110, 108, 112, 115, 113, 120])
```

다음 작업을 수행하세요:
1. 일일 수익률을 계산하세요 (전일 대비 변화율)
2. 최고가와 최저가를 구하세요
3. 가격이 평균보다 높은 날의 수를 구하세요
4. 연속으로 상승한 최대 일수를 구하세요
5. 5일 이동평균을 계산하세요


In [39]:
stock_prices = np.array([100, 102, 98, 105, 110, 108, 112, 115, 113, 120])

print("주식 가격 데이터:")
print(stock_prices)
print("\n" + "="*50)

# 1. 일일 수익률 계산
changes = np.diff(stock_prices)
daily = stock_prices[:-1]
daily_returns = changes / daily * 100
print(f"일일 수익률 (%): {daily_returns}")

# 2. 최고가와 최저가
max_price = np.max(stock_prices)
min_price = np.min(stock_prices)
print(f"최고가: {max_price}, 최저가: {min_price}")

# 3. 평균보다 높은 날의 수
avg = np.mean(stock_prices)
above_avg = np.sum(stock_prices > avg)
print(f"평균보다 높은 날의 수: {above_avg}일")

# 4. 연속 상승 최대 일수
price_changes = np.diff(stock_prices)
consecutive_rises = 0
max_consecutive = 0
for change in price_changes:
    if change > 0:
        consecutive_rises += 1
        max_consecutive = max(max_consecutive, consecutive_rises)  # 이제 정상 작동
    else:
        consecutive_rises = 0
print(f"연속 상승 최대 일수: {max_consecutive}일")

# 5. 5일 이동평균
def moving_average(data, window):
    return np.convolve(data, np.ones(window)/window, mode='valid')

ma_5 = moving_average(stock_prices, 5)
print(f"5일 이동평균: {ma_5}")

주식 가격 데이터:
[100 102  98 105 110 108 112 115 113 120]

일일 수익률 (%): [ 2.         -3.92156863  7.14285714  4.76190476 -1.81818182  3.7037037
  2.67857143 -1.73913043  6.19469027]
최고가: 120, 최저가: 98
평균보다 높은 날의 수: 5일


TypeError: 'numpy.int64' object is not callable

In [2]:
# 여기에 코드를 작성하세요
stock_prices = np.array([100, 102, 98, 105, 110, 108, 112, 115, 113, 120])

print("주식 가격 데이터:")
print(stock_prices)
print("\n" + "="*50)

# 1. 일일 수익률 계산
daily_returns = np.diff(stock_prices) / stock_prices[:-1] * 100
print(f"일일 수익률 (%): {daily_returns}")

# 2. 최고가와 최저가
max_price = np.max(stock_prices)
min_price = np.min(stock_prices)
print(f"최고가: {max_price}, 최저가: {min_price}")

# 3. 평균보다 높은 날의 수
above_avg_days = np.sum(stock_prices > np.mean(stock_prices))
print(f"평균보다 높은 날의 수: {above_avg_days}일")

# 4. 연속 상승 최대 일수
price_changes = np.diff(stock_prices)
consecutive_rises = 0
max_consecutive = 0
for change in price_changes:
    if change > 0:
        consecutive_rises += 1
        max_consecutive = max(max_consecutive, consecutive_rises)
    else:
        consecutive_rises = 0
print(f"연속 상승 최대 일수: {max_consecutive}일")

# 5. 5일 이동평균
def moving_average(data, window):
    return np.convolve(data, np.ones(window)/window, mode='valid')

ma_5 = moving_average(stock_prices, 5)
print(f"5일 이동평균: {ma_5}")
# 위의 TypeError는 max라는 변수를 이미 np.max(stock_prices)로 할당했기 때문에,
# 이후에 max() 함수를 호출할 때 파이썬 내장 max 함수가 아니라 numpy.int64 객체를 호출하게 되어 발생합니다.
# 따라서, max라는 변수명을 다른 이름(예: max_value)으로 바꾸거나, 
# max() 내장 함수를 사용할 부분에서 변수명을 피해야 합니다.

# 예시: 위 코드에서 max = np.max(stock_prices) 부분을 max_value = np.max(stock_prices)로 바꾸세요.
# 또는 아래 for문에서 max() 대신 np.maximum()을 사용하지 말고, 변수명을 바꿔주세요.

# 아래는 max라는 변수명을 사용하지 않고, 내장 max() 함수를 정상적으로 사용하는 예시입니다.

# (이미 위에서 max_price, min_price로 변수명을 사용하고 있으므로, 아래 for문에서 max_consecutive 변수명은 그대로 두고, max() 내장함수를 사용해도 무방합니다.)
# 만약 위에서 max라는 변수명을 꼭 써야 한다면, for문에서 max() 대신 np.maximum()을 사용하지 마세요.

# 결론: max라는 변수명을 내장함수와 겹치지 않게 바꾸세요.
# 예시:
# max_value = np.max(stock_prices)
# min_value = np.min(stock_prices)
# print(f"max : {max_value}, min : {min_value}")

# 또는, 이미 위에서 max_price, min_price를 사용하고 있으니, max라는 변수명을 아예 사용하지 않는 것이 좋습니다.


주식 가격 데이터:
[100 102  98 105 110 108 112 115 113 120]

일일 수익률 (%): [ 2.         -3.92156863  7.14285714  4.76190476 -1.81818182  3.7037037
  2.67857143 -1.73913043  6.19469027]
최고가: 120, 최저가: 98
평균보다 높은 날의 수: 5일
연속 상승 최대 일수: 2일
5일 이동평균: [103.  104.6 106.6 110.  111.6 113.6]


In [ ]:
# 5. 5일 이동평균
def moving_average(data, window):
    return np.convolve(data, np.ones(window)/window, mode='valid')

ma_5 = moving_average(stock_prices, 5)
# 5일 이동평균을 구하는 함수와 그 결과를 출력하는 코드입니다.
# 아래에서 각 코드와 함수에 대해 자세히 설명하겠습니다.

# moving_average 함수는 주어진 데이터(data)에 대해 지정한 window(여기서는 5일)만큼의 이동평균을 계산합니다.
# np.convolve 함수는 두 배열의 컨볼루션(합성곱)을 계산하는 함수입니다.
# 여기서 np.ones(window)/window는 길이가 window인 배열을 만들고, 각 원소를 window로 나누어 평균을 구할 수 있도록 합니다.
# 예를 들어 window=5라면, np.ones(5)는 [1,1,1,1,1]이 되고, np.ones(5)/5는 [0.2,0.2,0.2,0.2,0.2]가 됩니다.
# np.convolve(data, np.ones(window)/window, mode='valid')는 data 배열에서 연속된 5개 값의 평균을 구해줍니다.
# mode='valid'는 완전히 겹치는 구간에서만 결과를 반환하므로, 데이터의 양 끝에서 window만큼의 값이 부족한 부분은 계산하지 않습니다.

# 예를 들어, stock_prices가 [100, 110, 120, 130, 140, 150, 160]이라면,
# 첫 번째 5일 이동평균은 (100+110+120+130+140)/5 = 120.0
# 두 번째 5일 이동평균은 (110+120+130+140+150)/5 = 130.0
# 세 번째 5일 이동평균은 (120+130+140+150+160)/5 = 140.0
# 이런 식으로 계산됩니다.

# 왜 이렇게 문제를 해결했는가?
# 이동평균은 주가 등 시계열 데이터의 추세를 부드럽게 파악하기 위해 자주 사용됩니다.
# np.convolve를 사용하면 반복문 없이 빠르고 간단하게 이동평균을 계산할 수 있습니다.
# np.ones(window)/window를 곱하는 것은 window개 만큼의 값을 더한 뒤 window로 나누어 평균을 구하는 효과입니다.

print(f"5일 이동평균: {ma_5}")

In [4]:
# np.convolve와 mode='valid'를 이해할 수 있는 아주 간단한 예제를 들어 설명드리겠습니다.

import numpy as np

# 예제 데이터: [1, 2, 3, 4, 5]
data = np.array([1, 2, 3, 4, 5])
window = 3

# 이동평균을 직접 계산해봅시다.
# np.ones(window)/window는 [1,1,1]/3 = [1/3, 1/3, 1/3] 입니다.
kernel = np.ones(window) / window
print("커널:", kernel)

# np.convolve를 사용하여 이동평균을 구합니다.
ma = np.convolve(data, kernel, mode='valid')
print("이동평균 결과:", ma)

# mode='valid'는 완전히 겹치는 구간에서만 결과를 반환합니다.
# 즉, [1,2,3], [2,3,4], [3,4,5] 세 구간의 평균만 나옵니다.
# 계산 과정:
# (1+2+3)/3 = 2.0
# (2+3+4)/3 = 3.0
# (3+4+5)/3 = 4.0
# 따라서 결과는 [2.0, 3.0, 4.0]이 됩니다.

# mode='same'이나 'full'을 쓰면 결과가 달라집니다.
ma_same = np.convolve(data, kernel, mode='same')
print("mode='same' 결과:", ma_same)

ma_full = np.convolve(data, kernel, mode='full')
print("mode='full' 결과:", ma_full)

# 요약:
# - np.ones(window)/window는 window개수만큼의 평균을 구하기 위한 커널입니다.
# - mode='valid'는 데이터와 커널이 완전히 겹치는 부분만 결과로 반환합니다.

커널: [0.33333333 0.33333333 0.33333333]
이동평균 결과: [2. 3. 4.]
mode='same' 결과: [1. 2. 3. 4. 3.]
mode='full' 결과: [0.33333333 1.         2.         3.         4.         3.
 1.66666667]


## 📚 np.convolve와 mode='valid' 개념 학습

### 1. np.convolve란?
- **합성곱(Convolution)** 연산을 수행하는 함수
- 두 배열을 곱하고 합하는 연산
- **이동평균 계산**에 자주 사용됨

### 2. mode='valid'의 의미
- **'valid'**: 두 배열이 완전히 겹치는 부분만 계산
- **'same'**: 첫 번째 배열과 같은 크기로 결과 반환
- **'full'**: 두 배열이 조금이라도 겹치는 모든 부분 계산

### 3. 이동평균 계산 원리
```python
# 5일 이동평균 예시
data = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
window = 5

# np.ones(5)/5 = [0.2, 0.2, 0.2, 0.2, 0.2] (각 요소에 1/5를 곱함)
# 이는 각 요소에 동일한 가중치(1/5)를 주는 것과 같음
```


In [14]:
# 📚 np.convolve와 mode='valid' 쉬운 예제

print("=" * 60)
print("1. 기본 개념 이해")
print("=" * 60)

# 간단한 데이터
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(f"원본 데이터: {data}")

# 3일 이동평균을 위한 가중치
window = 3
weights = np.ones(window) / window
print(f"가중치 (1/3씩): {weights}")

print("\n" + "=" * 60)
print("2. mode='valid' vs mode='same' 비교")
print("=" * 60)

# mode='valid': 완전히 겹치는 부분만
result_valid = np.convolve(data, weights, mode='valid')
print(f"mode='valid' 결과: {result_valid}")
print(f"결과 길이: {len(result_valid)} (원본: {len(data)})")

# mode='same': 원본과 같은 길이
result_same = np.convolve(data, weights, mode='same')
print(f"mode='same' 결과: {result_same}")
print(f"결과 길이: {len(result_same)} (원본: {len(data)})")

print("\n" + "=" * 60)
print("3. 수동으로 이동평균 계산해보기")
print("=" * 60)

# 수동으로 3일 이동평균 계산
manual_avg = []
for i in range(len(data) - window + 1):
    avg = np.mean(data[i:i+window])
    manual_avg.append(avg)
    print(f"인덱스 {i}-{i+window-1}: {data[i:i+window]} → 평균: {avg:.2f}")

print(f"\n수동 계산 결과: {manual_avg}")
print(f"np.convolve 결과: {result_valid}")
print(f"결과가 같은가? {np.allclose(manual_avg, result_valid)}")


1. 기본 개념 이해
원본 데이터: [ 1  2  3  4  5  6  7  8  9 10]
가중치 (1/3씩): [0.33333333 0.33333333 0.33333333]

2. mode='valid' vs mode='same' 비교
mode='valid' 결과: [2. 3. 4. 5. 6. 7. 8. 9.]
결과 길이: 8 (원본: 10)
mode='same' 결과: [1.         2.         3.         4.         5.         6.
 7.         8.         9.         6.33333333]
결과 길이: 10 (원본: 10)

3. 수동으로 이동평균 계산해보기
인덱스 0-2: [1 2 3] → 평균: 2.00
인덱스 1-3: [2 3 4] → 평균: 3.00
인덱스 2-4: [3 4 5] → 평균: 4.00
인덱스 3-5: [4 5 6] → 평균: 5.00
인덱스 4-6: [5 6 7] → 평균: 6.00
인덱스 5-7: [6 7 8] → 평균: 7.00
인덱스 6-8: [7 8 9] → 평균: 8.00
인덱스 7-9: [ 8  9 10] → 평균: 9.00

수동 계산 결과: [np.float64(2.0), np.float64(3.0), np.float64(4.0), np.float64(5.0), np.float64(6.0), np.float64(7.0), np.float64(8.0), np.float64(9.0)]
np.convolve 결과: [2. 3. 4. 5. 6. 7. 8. 9.]
결과가 같은가? True


In [ ]:
# 🔧 지수 표기법 문제 해결 방법들

print("=" * 60)
print("지수 표기법 문제 해결")
print("=" * 60)

# 문제가 되는 데이터
customer_data = np.array([[1, 150000, 5, 365, 4.5],
                         [2, 75000, 3, 180, 3.8],
                         [3, 300000, 8, 500, 4.9],
                         [4, 45000, 2, 90, 3.2],
                         [5, 200000, 6, 300, 4.7]])

print("1. 기본 출력 (지수 표기법):")
print(customer_data)

print("\n" + "=" * 40)
print("2. 해결 방법들:")
print("=" * 40)

# 방법 1: np.set_printoptions 사용
print("\n방법 1: np.set_printoptions 사용")
np.set_printoptions(suppress=True, precision=2)
print(customer_data)

# 방법 2: format 지정
print("\n방법 2: format 지정")
for i, row in enumerate(customer_data):
    print(f"고객 {int(row[0]):2d}: {row[1]:8,.0f}원, {int(row[2]):2d}회, {int(row[3]):3d}일, {row[4]:.1f}점")

# 방법 3: 특정 열만 정수로 변환
print("\n방법 3: 특정 열만 정수로 변환")
customer_data_int = customer_data.copy()
customer_data_int[:, 0] = customer_data_int[:, 0].astype(int)  # ID
customer_data_int[:, 2] = customer_data_int[:, 2].astype(int)  # 구매횟수
customer_data_int[:, 3] = customer_data_int[:, 3].astype(int)  # 가입일수
print(customer_data_int)

# 방법 4: pandas 스타일로 출력
print("\n방법 4: 더 보기 좋게 출력")
print("고객ID | 구매금액    | 구매횟수 | 가입일수 | 평점")
print("-" * 50)
for row in customer_data:
    print(f"{int(row[0]):6d} | {row[1]:8,.0f}원 | {int(row[2]):6d}회 | {int(row[3]):6d}일 | {row[4]:.1f}점")

# 원래 설정으로 복원
np.set_printoptions()  # 기본값으로 복원


In [ ]:
# 🎯 실제 주식 데이터로 이동평균 이해하기

print("=" * 60)
print("실제 주식 데이터로 이동평균 이해")
print("=" * 60)

# 실제 주식 가격 데이터
stock_prices = np.array([100, 102, 98, 105, 110, 108, 112, 115, 113, 120])
print(f"주식 가격: {stock_prices}")

print("\n" + "=" * 40)
print("3일 이동평균 계산 과정:")
print("=" * 40)

# 3일 이동평균을 수동으로 계산
window = 3
for i in range(len(stock_prices) - window + 1):
    subset = stock_prices[i:i+window]
    avg = np.mean(subset)
    print(f"일 {i+1}-{i+3}: {subset} → 평균: {avg:.2f}")

# np.convolve로 계산
weights = np.ones(window) / window
ma_3 = np.convolve(stock_prices, weights, mode='valid')
print(f"\nnp.convolve 결과: {ma_3}")

print("\n" + "=" * 40)
print("5일 이동평균:")
print("=" * 40)

# 5일 이동평균
window = 5
weights = np.ones(window) / window
ma_5 = np.convolve(stock_prices, weights, mode='valid')
print(f"5일 이동평균: {ma_5}")

# 수동으로도 확인
print("\n수동 계산:")
for i in range(len(stock_prices) - window + 1):
    subset = stock_prices[i:i+window]
    avg = np.mean(subset)
    print(f"일 {i+1}-{i+5}: {subset} → 평균: {avg:.2f}")

print("\n" + "=" * 40)
print("왜 np.ones(window)/window를 사용하나?")
print("=" * 40)
print("1. np.ones(5) = [1, 1, 1, 1, 1]")
print("2. np.ones(5)/5 = [0.2, 0.2, 0.2, 0.2, 0.2]")
print("3. 각 요소에 동일한 가중치(1/5)를 주는 것")
print("4. 이는 단순 평균과 같음: (a+b+c+d+e)/5")
print("5. mode='valid'는 완전히 겹치는 부분만 계산")


## 문제 3: 종합 실무 문제 - 고객 데이터 분석

다음은 온라인 쇼핑몰의 고객 구매 데이터입니다:

```python
# 고객 ID, 구매금액, 구매횟수, 가입일수, 평점
customer_data = np.array([[1, 150000, 5, 365, 4.5],
                         [2, 75000, 3, 180, 3.8],
                         [3, 300000, 8, 500, 4.9],
                         [4, 45000, 2, 90, 3.2],
                         [5, 200000, 6, 300, 4.7],
                         [6, 120000, 4, 200, 4.1],
                         [7, 80000, 3, 150, 3.5],
                         [8, 250000, 7, 400, 4.8],
                         [9, 60000, 2, 120, 3.0],
                         [10, 180000, 5, 250, 4.3]])
```

다음 분석을 수행하세요:
1. VIP 고객을 선별하세요 (구매금액 상위 20%)
2. 고객 세그먼트를 나누세요 (구매금액 기준: 10만원 미만, 10-20만원, 20만원 이상)
3. 평점과 구매금액의 상관관계를 분석하세요
4. 고객 생애 가치(CLV)를 계산하세요 (구매금액 × 구매횟수 / 가입일수 × 365)
5. 각 세그먼트별 평균 CLV를 구하세요


In [13]:
# 여기에 코드를 작성하세요
customer_data = np.array([[1, 150000, 5, 365, 4.5],
                         [2, 75000, 3, 180, 3.8],
                         [3, 300000, 8, 500, 4.9],
                         [4, 45000, 2, 90, 3.2],
                         [5, 200000, 6, 300, 4.7],
                         [6, 120000, 4, 200, 4.1],
                         [7, 80000, 3, 150, 3.5],
                         [8, 250000, 7, 400, 4.8],
                         [9, 60000, 2, 120, 3.0],
                         [10, 180000, 5, 250, 4.3]])

print("고객 데이터 (ID, 구매금액, 구매횟수, 가입일수, 평점):")
print(customer_data)
print("\n" + "="*70)

# 1. VIP 고객 선별 (구매금액 상위 20%)
purchase_amounts = customer_data[:, 1]
# print(np.percentile(purchase_amounts, 0)) # 0 : 45000, 100 : 300000
vip_threshold = np.percentile(purchase_amounts, 80)  # 상위 20%
vip_customers = customer_data[customer_data[:, 1] >= vip_threshold]
print(f"VIP 고객 기준 (구매금액 {vip_threshold:,.0f}원 이상):")
print(vip_customers)
print()

# 2. 고객 세그먼트 분류
segments = np.zeros(len(customer_data), dtype=int)
segments[purchase_amounts < 100000] = 0  # 10만원 미만
segments[(purchase_amounts >= 100000) & (purchase_amounts < 200000)] = 1  # 10-20만원
segments[purchase_amounts >= 200000] = 2  # 20만원 이상

segment_names = ['10만원 미만', '10-20만원', '20만원 이상']
for i, name in enumerate(segment_names):
    count = np.sum(segments == i)
    print(f"{name} 세그먼트: {count}명")
print()

# 3. 평점과 구매금액의 상관관계
ratings = customer_data[:, 4]
correlation = np.corrcoef(purchase_amounts, ratings)[0, 1]
print(f"평점과 구매금액의 상관계수: {correlation:.3f}")
print()

# 4. 고객 생애 가치(CLV) 계산
purchase_counts = customer_data[:, 2]
days_since_join = customer_data[:, 3]
clv = (purchase_amounts * purchase_counts) / (days_since_join / 365)
print("고객별 CLV:")
for i, value in enumerate(clv):
    print(f"고객 {i+1}: {value:,.0f}원")
print()

# 5. 세그먼트별 평균 CLV
print("세그먼트별 평균 CLV:")
for i, name in enumerate(segment_names):
    segment_clv = clv[segments == i]
    if len(segment_clv) > 0:
        avg_clv = np.mean(segment_clv)
        print(f"{name}: {avg_clv:,.0f}원")


고객 데이터 (ID, 구매금액, 구매횟수, 가입일수, 평점):
[[1.00e+00 1.50e+05 5.00e+00 3.65e+02 4.50e+00]
 [2.00e+00 7.50e+04 3.00e+00 1.80e+02 3.80e+00]
 [3.00e+00 3.00e+05 8.00e+00 5.00e+02 4.90e+00]
 [4.00e+00 4.50e+04 2.00e+00 9.00e+01 3.20e+00]
 [5.00e+00 2.00e+05 6.00e+00 3.00e+02 4.70e+00]
 [6.00e+00 1.20e+05 4.00e+00 2.00e+02 4.10e+00]
 [7.00e+00 8.00e+04 3.00e+00 1.50e+02 3.50e+00]
 [8.00e+00 2.50e+05 7.00e+00 4.00e+02 4.80e+00]
 [9.00e+00 6.00e+04 2.00e+00 1.20e+02 3.00e+00]
 [1.00e+01 1.80e+05 5.00e+00 2.50e+02 4.30e+00]]

VIP 고객 기준 (구매금액 210,000원 이상):
[[3.0e+00 3.0e+05 8.0e+00 5.0e+02 4.9e+00]
 [8.0e+00 2.5e+05 7.0e+00 4.0e+02 4.8e+00]]

10만원 미만 세그먼트: 4명
10-20만원 세그먼트: 3명
20만원 이상 세그먼트: 3명

평점과 구매금액의 상관계수: 0.921

고객별 CLV:
고객 1: 750,000원
고객 2: 456,250원
고객 3: 1,752,000원
고객 4: 365,000원
고객 5: 1,460,000원
고객 6: 876,000원
고객 7: 584,000원
고객 8: 1,596,875원
고객 9: 365,000원
고객 10: 1,314,000원

세그먼트별 평균 CLV:
10만원 미만: 442,562원
10-20만원: 980,000원
20만원 이상: 1,602,958원
