In [2]:
import numpy as np

In [4]:
n = "\n-----------------------------------------------\n"

### **[실습] 데이터를 기반으로 배열 연산 수행**

다음과 같은 과일 판매량 데이터가 있습니다. 각 과일의 1분기와 2분기 판매량이 주어졌을 때, NumPy 배열을 사용하여 아래 문제를 해결하세요.

1. 1분기와 2분기의 과일별 총 판매량을 구하세요.
2. 과일별 평균 판매량을 구하세요.

- **데이터**:
    - 1분기 판매량: `[200, 340, 150, 400]` (사과, 배, 오렌지, 바나나)
    - 2분기 판매량: `[220, 300, 180, 420]` (사과, 배, 오렌지, 바나나)


In [7]:
sales_q1 = np.array([200, 340, 150, 400])
sales_q2 = np.array([220, 300, 180, 420])
sales_total = np.add(sales_q1, sales_q2)
sales_avg = np.divide(sales_total, 2) # 평균 판매량, float 타입으로 반환

print("1, 2분기 총 판매량 : ", sales_total, n)
print("과일 별 평균 판매량 :", sales_avg.astype(int), n)


1, 2분기 총 판매량 :  [420 640 330 820] 
-----------------------------------------------

과일 별 평균 판매량 : [210 320 165 410] 
-----------------------------------------------



### **[실습 1] 기본 산술 연산**


다음 두 배열을 사용하여 각각의 요소별로 덧셈, 뺄셈, 곱셈, 나눗셈을 수행하세요.


```python
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1, 2, 3, 4])
```

In [ ]:
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1, 2, 3, 4])

arr_add = np.add(arr1, arr2)
arr_sub = np.subtract(arr1, arr2)
arr_mul = np.multiply(arr1, arr2)
arr_div = np.divide(arr1, arr2)

print("덧셈 : ", arr_add, n)
print("뺄셈 : ", arr_sub, n)
print("곱셈 : ", arr_mul, n)
print("나눗셈 : ", arr_div, n)




덧셈 :  [11 22 33 44] 
--------------------------------

뺄셈 :  [ 9 18 27 36] 
--------------------------------

곱셈 :  [ 10  40  90 160] 
--------------------------------

나눗셈 :  [10. 10. 10. 10.] 
--------------------------------



### [**실습 2] Dot Product**

다음 두 배열 간의 내적 연산을 수행하세요.

```python
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
```

In [ ]:
arr1 = np.array([1, 2, 3]) # shape (3, )
arr2 = np.array([4, 5, 6]) # shape (3, )
# 1*4 + 2*5 + 3*6 = 4 + 10 + 18 = 32

dot_product = np.dot(arr1, arr2)
matmul = np.matmul(arr1, arr2)
dot_product2 = arr1 @ arr2

print(dot_product, n)
print(matmul, n)
print(dot_product2, n)


32 
-----------------------------------------------

32 
-----------------------------------------------

32 
-----------------------------------------------



### [**실습 3] 브로드캐스팅**

아래의 2차원 배열과 1차원 배열을 브로드캐스팅하여 더하세요.

```python
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
arr1d = np.array([10, 20, 30])
```

In [ ]:
arr2d = np.array([[1, 2, 3], [4, 5, 6]]) # shape (2, 3)
arr1d = np.array([10, 20, 30]) # shape (3, ) -> (1, 3) -> (2, 3)
#                [[10 20 30],
#                 [10 20 30]]

add_result = np.add(arr2d, arr1d)

print(add_result, n) # [[11 22 33],
                     #  [14 25 36]]

# TTS, Audio Engineering, 

