# Data Science
- 방대한 양의 데이터를 수집, 분성, 시각화하여 유의미한 정보를 추출하는 것
- 파이썬 패키지로는 numpy, pandas, matplotlib, seaborn 등이 주로 사용됨

---

# Numpy
- 대규모의 다차원 배열, 수치 연산을 지원하는 라이브러리리

In [26]:
!pip install numpy

In [27]:
!pip list

Package                   Version
------------------------- --------------
altair                    5.5.0
anyio                     4.10.0
argon2-cffi               25.1.0
argon2-cffi-bindings      25.1.0
arrow                     1.3.0
asttokens                 3.0.0
async-lru                 2.0.5
attrs                     25.3.0
babel                     2.17.0
beautifulsoup4            4.13.4
bleach                    6.2.0
blinker                   1.9.0
branca                    0.8.1
cachetools                6.2.0
certifi                   2025.8.3
cffi                      1.17.1
charset-normalizer        3.4.3
click                     8.2.1
colorama                  0.4.6
comm                      0.2.3
contourpy                 1.3.3
cycler                    0.12.1
debugpy                   1.8.16
decorator                 5.2.1
defusedxml                0.7.1
et_xmlfile                2.0.0
executing                 2.2.0
fastjsonschema            2.21.2
folium          

---

### ndarray 다차원 배열 생성

In [1]:
import numpy as np

In [29]:
# 1차원 배열
arr1d = np.array([2025, 9, 5, 11, 20])
today_arr = [2025, 9, 5, 11, 20]

print(arr, type(arr)) # 배열 형태로 출력 ndarray -> number dimension array
                      # 배열의 요소는 모두 같은 자료형이어야 함, Tab 공백으로 구분
print(today_arr1d, type(today_arr1d)) # 리스트 형태로 출력, 여러 요소를 , 구분자로 구분

# 2차원 배열
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2d, type(arr2d))


[[10 20]
 [30 40]] <class 'numpy.ndarray'>


NameError: name 'today_arr1d' is not defined

In [ ]:
arr = np.array((1, 2, 3, 4, 5))
print(arr, type(arr))

arr = np.array([1, 2, 3, 4, 5])
print(arr, type(arr))

# 인자로 list, tuple, dict, set 등의 자료형을 사용할 수 있음
arr = np.array(range(10))
print(arr, type(arr))

# 인자로 문자열을 사용할 수 있음
arr = np.array("Hello, World!")
print(arr, type(arr))


[1 2 3 4 5] <class 'numpy.ndarray'>
[1 2 3 4 5] <class 'numpy.ndarray'>
[0 1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>
Hello, World! <class 'numpy.ndarray'>


In [ ]:
arr = np.array([2025, 9, 5, 11, 20])

# 1차원 배열
# ndarray 속성
print(arr.shape)    # 형태 tuple 형태로 반환 (1차원 배열의 경우 요소 개수만을 반환)
                    # 1차원 배열일 경우 (5,) -> 뒤에 , 가 붙는 이유는 1차원 배열이기 때문
print(arr.ndim)     # 차원 수, 깊이 반환
print(arr.size)     # 요소 개수 반환
print(arr.dtype)    # 요소 자료형 반환
print(arr.itemsize) # 요소 크기 반환
print(arr.nbytes)   # 배열 전체 크기 반환

(5,)
1
5
int64
8
40


In [ ]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d)
print([[1, 2, 3], [4, 5, 6]])
print(type([[1, 2, 3], [4, 5, 6]]))
print("--------------------------------")
print(arr_2d.shape)    # 형태 tuple 형태로 반환 (행, 열) # 2차원 배열일 경우 (2, 3)
print(arr_2d.ndim)     # 차원 수, 깊이 반환
print(arr_2d.size)     # 요소 개수 반환 -> 행 * 열 6 출력
print(arr_2d.dtype)    # 요소 자료형 반환 -> int64 출력, 64비트 정수형
print(arr_2d.itemsize) # 요소 크기 반환 -> 8 출력, 4바이트 정수형, (8byte = 1bit)
print(arr_2d.nbytes)   # 배열 전체 크기 반환

index_result = arr_2d[0, 1] # 0행 1열 요소 반환
print(index_result)



[[1 2 3]
 [4 5 6]]
[[1, 2, 3], [4, 5, 6]]
<class 'list'>
--------------------------------
(2, 3)
2
6
int64
8
48
2


In [ ]:
arr_int = np.array([2025, 9, 5])
print(arr_int.dtype) # int64(8byte)

arr_float = np.array([1.234, 3.456, 9.876, 10], dtype=float) # 10은 10.0으로 저장
print(arr_float.dtype) # float64 

arr_bool = np.array([True, False, True], dtype=bool)
print(arr_bool.dtype) # bool

arr_str = np.array(["Hello", "World", "numpy-lib", "great"], dtype=str)
print(arr_str.dtype) # <U9 -> 9개의 문자열 배열 : 유니코드 9글자까지 저장 가능한 문자열

print(arr_float)



int64
float64
bool
<U9
[ 1.234  3.456  9.876 10.   ]


In [ ]:
# 형변환
arr1 = np.array([1.234, 3.456, 9.876, 9, 10])
arr2 = np.array([1.234, 3.456, 9.876, 9, 10], dtype=float)
arr3 = np.array([1.234, 3.456, 9.876, 9, 10], dtype=int)
arr4 = np.array([1.234, 3.456, 9.876, 9, 10], dtype=str)
arr5 = arr4
print(arr5)
# arr5는 문자열(str) 타입의 numpy 배열입니다. 
# 이 배열을 astype(int)로 정수형으로 변환하려고 하면,
# 문자열 원소 중 '1.234'와 같이 소수점이 포함된 문자열은 정수로 바로 변환할 수 없기 때문에
# ValueError가 발생합니다.
# 예를 들어, int('1.234')는 파이썬에서 허용되지 않습니다.
# 
# astype() 함수는 새로운 배열을 반환하며, 원본 배열(arr5)은 변하지 않습니다.
# 이런 방식을 out-of-place(아웃 오브 플레이스) 변환이라고 하며,
# 원본 배열 자체를 변경하는 in-place(인플레이스) 변환과는 다릅니다.
# numpy에서 astype()은 항상 새로운 배열을 반환하므로, 원본 배열은 그대로 유지됩니다.
# 
# 만약 문자열 배열을 정수형으로 변환하려면, 먼저 실수(float)로 변환한 뒤 정수로 변환해야 합니다.
# 예시:
arr6 = arr5.astype(float).astype(int)
print(arr6)
print(arr5)
print("--------------------------------")

print(arr1, type(arr1), arr1.dtype)
print(arr2, type(arr2), arr2.dtype)
print(arr3, type(arr3), arr3.dtype)
print(arr4, type(arr4), arr4.dtype)
print(arr5, type(arr5), arr5.dtype)

['1.234' '3.456' '9.876' '9' '10']
[ 1  3  9  9 10]
['1.234' '3.456' '9.876' '9' '10']
--------------------------------
[ 1.234  3.456  9.876  9.    10.   ] <class 'numpy.ndarray'> float64
[ 1.234  3.456  9.876  9.    10.   ] <class 'numpy.ndarray'> float64
[ 1  3  9  9 10] <class 'numpy.ndarray'> int64
['1.234' '3.456' '9.876' '9' '10'] <class 'numpy.ndarray'> <U5
['1.234' '3.456' '9.876' '9' '10'] <class 'numpy.ndarray'> <U5


##### Python list와 ndarray의 차이
- ndarray는 동일한 자료형만 저장 가능
- ndarry는 다차원인 경우, 중첩 배열은 동일한 크기만 허용
- 형태/길이를 확인하는 방법의 차이
    - Python list : len()
    - ndarray: ndarray.shape, ndarray.ndim, ndarray.size

In [ ]:
my_list = [2025, 9, 5, 'numpy', True]
print(my_list) # [2025, 9, 5, 'numpy', True]
# 파이썬 리스트는 다양한 자료형을 혼합해서 저장할 수 있음

my_list = [[1, 2, 3], [4, 5], [6]]
my_list2= [1, 2, 3, 4, 5, 6]
print(my_list) # [[1, 2, 3], [4, 5], [6]]
print(len(my_list)) # 3
print(my_list[0]) # [1, 2, 3]
print("--------------------------------")
print(my_list2) # [1, 2, 3, 4, 5, 6]
print(len(my_list2)) # 6
print(my_list2[0]) # 1


[2025, 9, 5, 'numpy', True]
[[1, 2, 3], [4, 5], [6]]
3
[1, 2, 3]
--------------------------------
[1, 2, 3, 4, 5, 6]
6
1


In [ ]:
arr = np.array([2025, 9, 5, 'numpy', True])
# arr = np.array([[1, 2, 3], [4, 5], [6]]) # 중첩 배열은 동일한 크기만 허용
# ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions.
# 3x3 행렬로 만들고, 값이 없는 곳은 빈 값('') 또는 np.nan 등으로 채울 수 있습니다.
# 예시 1: 빈 문자열로 채우기
arr_3x3 = np.array([
    [1, 2, 3],
    [4, 5, ''],
    [6, '', '']
])
print(arr_3x3)
print(arr_3x3.shape)  # (3, 3) -> 3x3 행렬

# 예시 2: np.nan으로 채우기 (실수형 배열이어야 함)
arr_3x3_nan = np.array([
    [1, 2, 3],
    [4, 5, np.nan],
    [6, np.nan, np.nan]
], dtype=float)
print(arr_3x3_nan)
print(arr_3x3_nan.shape)  # (3, 3)



print(arr) # ['2025' '9' '5' 'numpy' 'True'] -> 모두 문자열로 저장
print(arr.shape) # (5,) -> 1차원 배열
print(arr.ndim) # 1 -> 차원 수
print(arr.size) # 5 -> 요소 개수
print(arr.dtype) # <U21 -> 21개의 문자열 배열 : 유니코드 21글자까지 저장 가능한 문자열
print(arr.itemsize) # 84 -> 요소 크기
print(arr.nbytes) # 420 -> 배열 전체 크기


[['1' '2' '3']
 ['4' '5' '']
 ['6' '' '']]
(3, 3)
[[ 1.  2.  3.]
 [ 4.  5. nan]
 [ 6. nan nan]]
(3, 3)
['2025' '9' '5' 'numpy' 'True']
(5,)
1
5
<U21
84
420


##### 특정 수로 초기화된 ndarray 생성

In [ ]:
# zeros
# arr = np.zeros()
# TypeError: zeros() missing required argument 'shape' (pos 0)
arr = np.zeros((3,3)) # shape 전달달
print(arr, arr.dtype)
arr1 = np.zeros((3,3)).astype(int)
print(arr1, arr1.dtype)

# ones
arr = np.ones((5,2))
print(arr, arr.dtype)

# full
# arr = np.full((4,1))
# TypeError: full() missing 1 required positional argument: 'fill_value'
arr = np.full((4,1),9.0) # shape, fill_value
print(arr, arr.dtype)

arr = np.full((4,),7) # shape, fill_value
print(arr, arr.dtype)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] float64
[[0 0 0]
 [0 0 0]
 [0 0 0]] int64
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]] float64
[[9.]
 [9.]
 [9.]
 [9.]] float64
[7 7 7 7] int64


In [49]:
arr = np.array([[10, 20], [30, 40]])
print(arr.shape)

# 원본 ndarray 가 있을때 똑.같.은. shape colume by row 를 따와서 채워준다.
# zeros_like
print(np.zeros_like(arr))

# ones_like
print(np.ones_like(arr))

# full_liked
print(np.full_like(arr, 9))

(2, 2)
[[0 0]
 [0 0]]
[[1 1]
 [1 1]]
[[9 9]
 [9 9]]


#### 수열 생성
- np.arange(start, end, step)
    - start : 시작하는 숫자
    - end : 끝나는 숫자 + 1
    - step: start~end 증가하는 간격

In [50]:
arr = np.arange(1, 10, 1.3)
print(arr, type(arr), arr.dtype, arr.size, arr.shape, sep="\n")
arr = np.arange(10)
print(arr)

[1.  2.3 3.6 4.9 6.2 7.5 8.8]
<class 'numpy.ndarray'>
float64
7
(7,)
[0 1 2 3 4 5 6 7 8 9]


- np.linsapce(start, end, num)
    - start : 시작하는 숫자
    - end : 끝나는 숫자(포함)
    - num : 결과로 만들어진 수열의 요소 갯수

    - start 이상 end 이하의 범위에서 num의 갯수 만큼 요소를 만들어라.

In [51]:
arr = np.linspace(0, 10, 5)
print(arr)

arr = np.linspace(0, 10, 4)
print(arr)

[ 0.   2.5  5.   7.5 10. ]
[ 0.          3.33333333  6.66666667 10.        ]


In [53]:
arr = np.linspace(0, 10)
print(arr) # 기본적으로 50의 num을 갖는다. 50개 요소로 나뉜다.

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]


In [54]:
arr = np.linspace(10)
print(arr)

TypeError: linspace() missing 1 required positional argument: 'stop'

- np.logspace(start_exp, end_exp, num, base)
    - start_exp: 시작 지수
    - end_exp: 끝 지수
    - num: 결과로 만들어진 수열의 요소 갯수
    - base: 밑 (기본값 = 10)

In [ ]:
# np.logspace() 함수는 로그 스케일(지수적으로 증가하는)로 숫자 배열을 생성할 때 사용합니다.
# 예를 들어, 10^0 부터 10^3까지 4개의 값을 생성해보겠습니다.

arr = np.logspace(0, 3, 4)
print(arr)  # [   1.   10.  100. 1000.]

# 위 결과는 10의 0제곱(1), 1제곱(10), 2제곱(100), 3제곱(1000)으로 이루어진 배열입니다.
# base 파라미터를 2로 바꾸면 2의 거듭제곱 배열이 생성됩니다.

arr2 = np.logspace(1, 4, 4, base=2)
print(arr2)  # [ 2.  4.  8. 16.]

# logspace는 데이터가 지수적으로 증가하거나 감소하는 경우에 유용하게 사용됩니다.


- [참고] 지수 | 로그 
    - 지수 : 거듭제곱 $a^x=b$에서 x
    - 밑 : 거듭제곱될 수 $a^x=b$에서 a
    - 로그 : 밑과 거듭제곱 결과로부터 지수를 반환 $log_a{b} = x$
    - 자연로그 : 밑이 자연상수e (2.718...)인 로그
    - 상용로그 : 밑이 10인 로그


In [55]:
arr = np.logspace(1, 3, 4)
print(arr)

[  10.           46.41588834  215.443469   1000.        ]


### **[실습] 다양한 방법으로 배열 생성**

<aside>
❓

NumPy를 사용하여 다음과 같은 배열을 생성해 보세요.

1. 크기가 4x3인 모든 값이 0인 배열
2. 크기가 3x3인 모든 값이 1인 배열
3. 0에서 20까지 5씩 증가하는 값으로 구성된 배열
4. 0과 1 사이의 4개의 등간격 값을 가진 배열
5. *크기가 2x2인 정규 분포로 구성된 배열*
</aside>

In [ ]:
arr = np.zeros((4,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [58]:
arr = np.ones((3,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [62]:
arr = np.arange(0, 21, 5)
print(arr)

[ 0  5 10 15 20]


In [4]:
arr = np.linspace(0, 1, 4)
print(arr)

[0.         0.33333333 0.66666667 1.        ]


In [ ]:
# 크기가 2x2인 정규 분포로 구성된 배열을 만들기 위해서는 numpy의 random 모듈에서 randn 함수를 사용하면 됩니다.
# np.random.randn(2, 2)는 평균이 0이고 표준편차가 1인 정규 분포를 따르는 2x2 배열을 생성합니다.
# 정규 분포는 데이터가 평균을 중심으로 좌우 대칭의 종 모양(벨 커브)을 이루는 확률 분포입니다.
# 평균을 기준으로 데이터가 퍼져 있으며, 평균에서 멀어질수록 값이 나올 확률이 낮아집니다.
# 통계, 자연과학, 머신러닝 등 다양한 분야에서 널리 사용됩니다.

# 평균과 표준 편차를 가지고 있는 배열
# 예시:

arr = np.random.randn(2, 2) # randn : 표준정규분포를 만들어내는 함수
print(arr)

[[ 0.09163759 -0.50206589]
 [ 0.45693152 -0.98241954]]


In [59]:
arr = np.random.normal(loc=0, scale=1, size=(2, 2))
print(arr)
# np.random.normal 함수는 정규분포(가우시안 분포)를 따르는 난수를 생성할 때 사용합니다.
# 이 함수는 평균(loc), 표준편차(scale), 그리고 생성할 배열의 크기(size)를 인자로 받습니다.
# np.random.randn 함수가 평균 0, 표준편차 1인 '표준정규분포'에서 난수를 생성하는 것과 달리,
# np.random.normal은 평균과 표준편차를 직접 지정할 수 있어 다양한 정규분포를 만들 수 있습니다.
# 예를 들어, 평균이 3이고 표준편차가 2인 2x2 배열을 만들고 싶다면 다음과 같이 작성합니다.
# loc는 "location"의 약어로, np.random.normal 함수에서 정규분포의 "평균"을 의미합니다.
# 즉, loc=3이면 평균이 3인 정규분포에서 난수를 생성합니다.

arr = np.random.normal(loc=3, scale=2, size=(2, 2))
print(arr)


[[ 0.48236702 -0.26710532]
 [-0.74572476  1.01939308]]
[[3.45589252 3.69079067]
 [4.65984146 2.75201939]]


---

### ndarray indexing & 
#### n차원 배열을 가지고 인덱싱, 슬라이싱 배워보기

In [32]:
# 1차원 배열 인덱싱
arr = np.arange(1, 11)
print(arr)
print(arr[1], arr[3], arr[9])
# print(arr[1], arr[3], arr[10])
# IndexError: index 10 is out of bounds for axis 0 with size 10
print(arr[-1], arr[-5])

[ 1  2  3  4  5  6  7  8  9 10]
2 4 10
10 6


In [59]:
# 2차원 배열 인덱싱
arr_2d = np.array([[10, 20, 30], [40, 50 , 60]])
print(arr_2d, arr_2d.shape, sep='\n')
print(arr_2d[1], arr_2d[1][1], sep='\n')
print("-------------------------------")
print(arr_2d[0][0])
print(arr_2d[0, 1])
print(arr_2d[(0,2)])

[[10 20 30]
 [40 50 60]]
(2, 3)
[40 50 60]
50
-------------------------------
10
20
30


In [63]:
arr = np.array([[11, 22, 33], [44, 55, 66], [77, 88, 99]])

print(arr)
print(arr[(1,0)]) # 44
print(arr[2,1]) # 88
print(arr[(-1, -2)]) # 88 (음수 인덱싱 활용용)

[[11 22 33]
 [44 55 66]
 [77 88 99]]
44
88
88


In [75]:
arr = np.arange(1,11)
print(arr)
print(arr[2:-3])    # [3 4 5 6 7]
print(arr[:10:2])    # [1 3 5 7 9]
print(arr[4:])    # [5 6 7 8 9 10]
print(arr[:-3])    # [1 2 3 4 5 6 7]
print(arr[::-1])    # [10 9 8 7 6 5 4 3 2 1]

[ 1  2  3  4  5  6  7  8  9 10]
[3 4 5 6 7]
[1 3 5 7 9]
[ 5  6  7  8  9 10]
[1 2 3 4 5 6 7]
[10  9  8  7  6  5  4  3  2  1]


In [19]:
# 2차원 배열 슬라이싱
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(arr)
print("------------")
print(arr[0:2, 1:2]) # [행 슬라이싱, 열 슬라이싱]

print("------------")
print(arr[0:2,:]) # print(arr[:2]) -> 행 슬라이싱만 적어줘도 됨
# 1
# [[10 20 30]
#  [40 50 60]]
print("------------")
print(arr[:, 1: ])
# 2
# [[20 30]
#  [50 60]
#  [80 90]]
print("------------")
print(arr[:2, 1:])
# 3
# [[20 30]
#  [50 60]]

# 슬라이싱 = shape 유지 (차원 유지)
print("------------")
print(arr[:-1, 0:1], arr[:-1, 0:1].shape)
# index 접근 -> 값을 꺼내서 반환 (차원 제거)
print("------------")
print(arr[:-1, 0], arr[:-1, 0].shape)
print(arr[:-1, 1], arr[:-1, 1].shape)
print(arr[:-1, 2], arr[:-1, 2].shape)

[[10 20 30]
 [40 50 60]
 [70 80 90]]
------------
[[20]
 [50]]
------------
[[10 20 30]
 [40 50 60]]
------------
[[20 30]
 [50 60]
 [80 90]]
------------
[[20 30]
 [50 60]]
------------
[[10]
 [40]] (2, 1)
------------
[10 40] (2,)
[20 50] (2,)
[30 60] (2,)


In [ ]:
# 1차원 배열  fancy indexing

# 인덱싱 : 인덱스를 하나 지정해서 그 인덱스에 접근하는 것(가져오는 것)
# fancy 인덱싱 : 정수 배열을 사용해서 여러 인덱스에 있는 값을 한번에 추출출

arr = np.arange(5, 31, 5)
print(arr)
# print(arr[1, 3, 5])
# IndexError: too many indices for array: array is 1-dimensional, but 3 were indexed
print(arr[[1,3,5]]) # list 로 넘겨줘야한다.

indicies = [1, 3, 5]
print(arr[indicies])

[ 5 10 15 20 25 30]
[10 20 30]
[10 20 30]


In [39]:
# 2차원 배열 fancy indexing
arr = np.array([[5, 10, 15, 20],
                [25, 30, 35, 40],
                [45, 50, 55, 60]
                ])
# [10 35]
indices1 = [0, 1] # 1행 2열
indices2 = [1, 2] # 2행 3열

print(arr[indices1, indices2])
print("---------")
print(arr[[0, 1],[1, 2]])

# [25 55]
indices3 = [1, 2]
indices4 = [0, 2]
print(arr[indices3, indices4])
print(arr[[1, 2], [0, 2]])
print("---------")
# 왜 결과가 35, 35가 나올까요?
# arr[[1][0], [2,2]]에서 [1][0]은 1입니다. 즉, arr[1, [2,2]]와 동일하게 동작합니다.
# 즉, 1행의 2열, 1행의 2열(두 번) 값을 가져오므로 [35 35]가 출력됩니다.
print(arr[[1][0], [2,2]]) 
print(arr[[0,2],[2,2]])

[10 35]
---------
[10 35]
[25 55]
[25 55]
---------
[35 35]
[15 55]


In [ ]:
# fancy indexing(팬시 인덱싱)은 정수 배열(리스트, numpy 배열 등)을 사용하여 여러 위치의 값을 한 번에 추출할 수 있는 방법입니다.
# 2차원 배열에서 fancy indexing을 사용하면, 각 인덱스 쌍에 해당하는 원소를 한 번에 가져올 수 있습니다.

# 예제: 아래와 같이 arr이 있을 때,
# arr = np.array([[5, 10, 15, 20],
#                 [25, 30, 35, 40],
#                 [45, 50, 55, 60]])
# arr[[1, 2], [0, 2]]는 (1,0) 위치와 (2,2) 위치의 값을 가져옵니다.

print("fancy indexing 예제:")
print("arr =\n", arr)
print("arr[[1, 2], [0, 2]] =", arr[[1, 2], [0, 2]])  # [25 55]
# (1,0) 위치의 값: 25, (2,2) 위치의 값: 55


In [ ]:
# 실무에서 fancy indexing은 다음과 같은 상황에서 자주 사용됩니다.
# - 대용량 데이터에서 조건에 맞는 여러 행/열을 한 번에 추출할 때
# - 데이터 전처리 과정에서 결측치, 이상치 등 특정 인덱스의 값을 빠르게 선택/수정할 때
# - 이미지, 시계열 등 다차원 데이터에서 복잡한 위치의 값을 효율적으로 추출할 때

# 예를 들어, 고객 데이터에서 VIP 고객의 인덱스만 모아 해당 고객의 정보만 추출하거나,
# 센서 데이터에서 이상치로 판별된 인덱스만 골라내어 분석할 때 유용합니다.

# 딥러닝/머신러닝/AI 학습자에게:
# fancy indexing은 numpy, pandas 등에서 데이터셋을 다룰 때 매우 자주 사용됩니다.
# 예를 들어, 미니배치 학습 시 무작위로 샘플 인덱스를 뽑아 데이터를 추출하거나,
# 특정 클래스에 해당하는 데이터만 골라내어 분석할 때 필수적입니다.
# 또한, 신경망의 파라미터 업데이트, 마스킹, 샘플링 등 다양한 곳에서 활용됩니다.

# 실습을 많이 해보면서 fancy indexing에 익숙해지면, 데이터 처리 속도와 코드 효율성이 크게 향상됩니다!

In [20]:
# boolean indexing
arr = np.arange(1, 6) # [1 2 3 4 5]
                      #  T F F F T
bools = [True, False, False, False, True]
print(arr[bools])

[1 5]


In [21]:
# 2차원 배열 boolean indexing
arr = np.array([
               [3, 6, 9],
               [12, 15, 18],
               [21, 24, 27]
               ])

print(arr[arr > 10])
print(arr[arr % 2 == 0])

[12 15 18 21 24 27]
[ 6 12 18 24]


In [44]:
# 핵심 문제 5개

# 1. 1부터 20까지의 정수를 원소로 갖는 1차원 numpy 배열 arr1을 생성하고, 짝수만 출력하세요.
arr1 = np.arange(1, 21)
print("문제 1:", arr1[arr1 % 2 == 0])

문제 1: [ 2  4  6  8 10 12 14 16 18 20]


In [50]:
# 2. 3행 4열의 0으로 채워진 numpy 배열 arr2를 만들고, 모든 원소를 7로 바꾼 후 출력하세요.
arr2 = np.zeros((3, 4), dtype=int)
# arr2[:] = 7
arr2 = np.full_like(arr2, 7)
print("문제 2:\n", arr2)

문제 2:
 [[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [51]:
# 3. 1차원 배열 arr3 = np.array([5, 10, 15, 20, 25])에서 인덱스 1~3까지의 값을 슬라이싱하여 출력하세요.
arr3 = np.array([5, 10, 15, 20, 25])
print("문제 3:", arr3[1:4])

문제 3: [10 15 20]


In [57]:
# 4. 2차원 배열 arr4 = np.array([[1,2,3],[4,5,6],[7,8,9]])에서 첫 번째 행과 마지막 열을 각각 출력하세요.
arr4 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr4, "\nshape :", arr4.shape)
print("문제 4 - 첫 번째 행:", arr4[0])
print("문제 4 - 첫 번째 행:", arr4[0, :])
print("문제 4 - 마지막 열:", arr4[:, -1])

[[1 2 3]
 [4 5 6]
 [7 8 9]] 
shape : (3, 3)
문제 4 - 첫 번째 행: [1 2 3]
문제 4 - 첫 번째 행: [1 2 3]
문제 4 - 마지막 열: [3 6 9]


In [64]:
# 5. 평균이 0, 표준편차가 1인 정규분포에서 난수 5개로 이루어진 1차원 배열 arr5를 생성하고, 평균과 표준편차를 출력하세요.
arr5 = np.random.randn(5)
arr6 = np.random.normal(loc=0, scale=1, size=(1,5))
print(arr5)
print(arr6)

# print("문제 5 - 배열:", arr5)
# print("문제 5 - 평균:", arr5.mean())
# print("문제 5 - 표준편차:", arr5.std())


[ 0.37802979 -0.5745406  -1.90284994 -0.6444643  -0.18707857]
[[ 0.05426694 -0.34587542 -0.89936575 -1.49877186 -0.70151821]]


In [43]:
arr = np.arange(1,21)
print(arr)
print(arr % 2 == 0)
# 왜 print(arr[False, True, ..., False, True])는 안 될까?
# arr의 길이(20)와 불리언 리스트의 길이(20)가 정확히 일치하면 동작하지만,
# 실수로 길이가 다르면 에러가 발생함. 
# arr[arr % 2 == 0]은 arr의 각 원소마다 조건을 적용해서 True/False 배열을 자동으로 만들어주기 때문에 더 안전하고 편리함.
print(arr[arr % 2 == 0])  # arr[False, True, ..., False, True]와 같은 결과를 얻을 수 있음
print(arr[False, True, False, True, False, True, False, True, False, True, False, True,
 False, True, False, True, False, True, False, True])

# 올바르게 20개의 bool 자료 결과 값을 넣었는데 왜 빈 [] 가 나오는거지?
# → arr[False, True, ...]에서 bool 리스트를 여러 줄에 걸쳐 쓸 때, 
#   줄바꿈 뒤에 콤마(,)가 빠지면 Python이 한 줄로 인식하지 않고 
#   두 번째 줄부터는 새로운 인자로 처리해서 결과가 달라집니다.
#   즉, 아래처럼 콤마가 빠지면 의도한 대로 동작하지 않습니다.
#   반드시 각 줄 끝에 콤마(,)를 붙여야 합니다.

# 잘못된 예시 (줄바꿈 뒤 콤마 없음 → 빈 배열 출력)
# print(arr[False, True, False, True, False, True, False, True, False, True, False, True
#  False, True, False, True, False, True, False, True])  # 빈 배열 출력

# 올바른 예시 (각 줄 끝에 콤마 추가)
print(arr[
    False, True, False, True, False, True, False, True, False, True,
    False, True, False, True, False, True, False, True, False, True
])  # 짝수만 출력됨

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[False  True False  True False  True False  True False  True False  True
 False  True False  True False  True False  True]
[ 2  4  6  8 10 12 14 16 18 20]
[]
[]


In [ ]:
- np.all(): (조건식) -> and 와 비슷한 연산
- ndarray의 모든 요소가 조건을 만족할 때 True 반환
- np.any(): (조건식) -> or 와 비슷한 연산
- ndarray의 모든 요소 중 하나라도 조건을 만족할 때 True 반환환

In [68]:
arr = np.array([10, 20, 30, 40, -50])

is_all_positive = np.all(arr > 0)

if is_all_positive:
    print("모든 수는 양수입니다")
else:
    print("모든 수가 양수는 아닙니다.")


모든 수가 양수는 아닙니다.


In [69]:
has_positive = np.any(arr > 0)

if has_positive:
    print('양수가 포함되어 있습니다.')
else:
    print('모든 수가 음수입니다.')

양수가 포함되어 있습니다.
