### ndarray_연산

In [1]:
import numpy as np

#### 기본 연산

In [5]:
n = "\n--------------------------------\n"

In [ ]:
# ndarray의 reshape() 메서드
# 1차원 배열을 여러 개의 행과 열로 재배열하는 메서드
# 주의할 점 : 배열의 총 요소 수와 재배열할 행과 열의 곱이 같아야 한다.

In [7]:
arr_a = np.arange(1, 10).reshape(3, 3)
print(arr_a, n, arr_a.shape, n)
arr_a

[[1 2 3]
 [4 5 6]
 [7 8 9]] 
--------------------------------
 (3, 3) 
--------------------------------



array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
arr_b = np.full_like(arr_a, 3)
print(arr_a, n, arr_a.shape, n)
print(arr_b, n, arr_b.shape, n)

[[1 2 3]
 [4 5 6]
 [7 8 9]] 
--------------------------------
 (3, 3) 
--------------------------------

[[3 3 3]
 [3 3 3]
 [3 3 3]] 
--------------------------------
 (3, 3) 
--------------------------------



In [20]:
# 덧셈
print(arr_a + arr_b, n)
print(np.add(arr_a, arr_b))

[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]] 
--------------------------------

[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [21]:
# 뺄셈
print(arr_a - arr_b, n)
print(np.subtract(arr_a, arr_b))

[[-2 -1  0]
 [ 1  2  3]
 [ 4  5  6]] 
--------------------------------

[[-2 -1  0]
 [ 1  2  3]
 [ 4  5  6]]


In [22]:
# 곱셈
print(arr_a * arr_b, n)
print(np.multiply(arr_a, arr_b))

[[ 3  6  9]
 [12 15 18]
 [21 24 27]] 
--------------------------------

[[ 3  6  9]
 [12 15 18]
 [21 24 27]]


In [ ]:
# 나눗셈
print(arr_a / arr_b, n, (arr_a / arr_b).astype(int), n)
print(np.divide(arr_a, arr_b))

[[0.33333333 0.66666667 1.        ]
 [1.33333333 1.66666667 2.        ]
 [2.33333333 2.66666667 3.        ]] 
--------------------------------
 [[0 0 1]
 [1 1 2]
 [2 2 3]] 
--------------------------------

[[0.33333333 0.66666667 1.        ]
 [1.33333333 1.66666667 2.        ]
 [2.33333333 2.66666667 3.        ]]


In [30]:
# 특수연산 1 : 거듭제곱
print(arr_a, n, arr_b, n)
print(arr_a ** arr_b, n)
print(np.power(arr_a, arr_b), n) # 거듭제곱(power, 제곱 연산) np.power(base, exponent)
print(np.sqrt(arr_a), n) # 제곱근
print(np.square(arr_a), n) # 제곱

print(np.exp(arr_a), n) # 지수함수
print(np.log(arr_a), n) # 자연로그
print(np.log10(arr_a), n) # 상용로그

[[1 2 3]
 [4 5 6]
 [7 8 9]] 
--------------------------------
 [[3 3 3]
 [3 3 3]
 [3 3 3]] 
--------------------------------

[[  1   8  27]
 [ 64 125 216]
 [343 512 729]] 
--------------------------------

[[  1   8  27]
 [ 64 125 216]
 [343 512 729]] 
--------------------------------

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]] 
--------------------------------

[[ 1  4  9]
 [16 25 36]
 [49 64 81]] 
--------------------------------

[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]] 
--------------------------------

[[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]
 [1.94591015 2.07944154 2.19722458]] 
--------------------------------

[[0.         0.30103    0.47712125]
 [0.60205999 0.69897    0.77815125]
 [0.84509804 0.90308999 0.95424251]] 
--------------------------------



In [26]:
# 특수연산 2: 몫
print(arr_a // arr_b, n)
print(np.floor_divide(arr_a, arr_b))

[[0 0 1]
 [1 1 2]
 [2 2 3]] 
--------------------------------

[[0 0 1]
 [1 1 2]
 [2 2 3]]


In [27]:
# 특수연산 3 : 나머지
print(arr_a % arr_b, n)
print(np.mod(arr_a, arr_b), n)

[[1 2 0]
 [1 2 0]
 [1 2 0]] 
--------------------------------

[[1 2 0]
 [1 2 0]
 [1 2 0]] 
--------------------------------



### **[실습] 데이터를 기반으로 배열 연산 수행**

다음과 같은 과일 판매량 데이터가 있습니다. 각 과일의 1분기와 2분기 판매량이 주어졌을 때, NumPy 배열을 사용하여 아래 문제를 해결하세요.

1. 1분기와 2분기의 과일별 총 판매량을 구하세요.
2. 과일별 평균 판매량을 구하세요.

- **데이터**:
    - 1분기 판매량: `[200, 340, 150, 400]` (사과, 배, 오렌지, 바나나)
    - 2분기 판매량: `[220, 300, 180, 420]` (사과, 배, 오렌지, 바나나)


In [38]:
arr_1 = np.array([200, 340, 150, 400])
arr_2 = np.array([220, 300, 180, 420])
arr_add = np.add(arr_1, arr_2)

print("1, 2분기 총 판매량 : ", arr_add, n)
print("과일 별 평균 판매량 :", (arr_add / 2).astype(int), n)


1, 2분기 총 판매량 :  [420 640 330 820] 
--------------------------------

과일 별 평균 판매량 : [210 320 165 410] 
--------------------------------



### **[실습 1] 기본 산술 연산**


다음 두 배열을 사용하여 각각의 요소별로 덧셈, 뺄셈, 곱셈, 나눗셈을 수행하세요.


```python
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1, 2, 3, 4])
```

In [40]:
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1, 2, 3, 4])

arr_add = np.add(arr1, arr2)
arr_sub = np.subtract(arr1, arr2)
arr_mul = np.multiply(arr1, arr2)
arr_div = np.divide(arr1, arr2)

print("덧셈 : ", arr_add, n)
print("뺄셈 : ", arr_sub, n)
print("곱셈 : ", arr_mul, n)
print("나눗셈 : ", arr_div, n)




덧셈 :  [11 22 33 44] 
--------------------------------

뺄셈 :  [ 9 18 27 36] 
--------------------------------

곱셈 :  [ 10  40  90 160] 
--------------------------------

나눗셈 :  [10. 10. 10. 10.] 
--------------------------------



##### broadcasting 연산

- 두 배열의 shape이 다르면 broadcasting 연산을 수행한다.
- shape이 작은 쪽이 큰 쪽에 맞춰 확장한다.
> 조건
>- 두 배열의 행 또는 열이 일치해야 확장 가능하다. 
>   - **(확장에 대한 요소를 정할 수 있기 때문이다. 중요)**
>- 크기가 1인 경우 무조건 확장 가능하다.
>- shape이 다른 경우 마지막 축부터 차원이 동일한지 비교한다.

In [ ]:
arr_a = np.arange(1, 10).reshape(3, 3)

result_arr1 = arr_a * np.array([[5, 5, 5], [5, 5, 5], [5, 5, 5]]) # shape (3, 3) ndim 2
# 같은 shape의 배열끼리 연산 시 같은 요소의 위치별 각 요소별로 연산 수행

result_arr2 = arr_a * np.array([5, 5, 5]) # shape (3,) ndim 1
# 배열의 행과 열의 개수가 다른 경우 브로드캐스팅 연산 수행
# (3, 3)
# 1단계 : (3,) -> 차원을 맞춰준다 (1, 3) -> 브로드캐스팅 연산 수행
# 2단계 : (1, 3) -> 축을 보니 3, 3 동일
# 3단계 : (3, 3) -> 차원을 보니 3, 1 -> 3, 3 형태로 변환

result_arr3 = np.array([5]) # shape (1,) ndim 0
# 1단계 : (1,) -> 차원을 맞춰준다 (1, 1) -> 브로드캐스팅 연산 수행
# 2단계 : (1, 1) -> 축을 보니 3, 1 다름 -> (1, 3) 형태로 변환
# 3단계 : (1, 3) -> 차원을 보니 3, 1 다름 -> (3, 3) 형태로 변환

result_arr4 = arr_a * 5 # 5 : scalar값 , shape (3, 3), ndim 0
# 


print(arr_a, n)
print(result_arr1, n)
print(result_arr2, n)
print(result_arr3, n)
print(result_arr4, n)

# 1 : 차원을 맞춰라
# 2 : 축을 보니 같으면 넘어가고 다르면 형태를 맞춰라
# 3 : 차원을 보니 같으면 넘어가고 다르면 형태를 맞춰라


[[1 2 3]
 [4 5 6]
 [7 8 9]] 
--------------------------------

[[ 5 10 15]
 [20 25 30]
 [35 40 45]] 
--------------------------------

[[ 5 10 15]
 [20 25 30]
 [35 40 45]] 
--------------------------------

[5] 
--------------------------------

[[ 5 10 15]
 [20 25 30]
 [35 40 45]] 
--------------------------------



In [ ]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]]) # shape (2, 3) ndim 2
arr2 = np.array([5, 10, 15]) # shape (3,) ndim 1

print(arr1 + arr2) # shape (2, 3) ndim 2
# 1단계 : (3,) -> 차원을 맞춰준다 (1, 3) -> 브로드캐스팅 연산 수행
# 2단계 : (1, 3) -> 축을 보니 3, 3 동일
# 3단계 : (2, 3) -> 차원을 보니 2, 1 -> (2, 3) 형태로 변환





[[ 6 12 18]
 [ 9 15 21]]


In [47]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]]) # shape (2, 3) ndim 2
arr2 = np.array([[100], [200]]) # shape (2, 1) ndim 2

print(arr1 + arr2) # shape (2, 3) ndim 2
# 1단계 : 차원은 동일
# 2단계 : 축을 보니 3, 1 다름 -> (2, 3) 형태로 변환
# [[100]   -> [[100 100 100]
#  [200]]   -> [200 200 200]]


[[101 102 103]
 [204 205 206]]


In [48]:
arr1 = np.array([1, 2, 3]) # shape (3,) ndim 1
arr2 = np.array([[4], [5], [6]]) # shape (3, 1) ndim 2

print(arr1 + arr2) # shape (3, 1) ndim 2
'''
(3, )          (1, 3)        (3, 3)
[1, 2, 3]      [[1, 2, 3]]   [[1, 2, 3],
                              [1, 2, 3],
                              [1, 2, 3]]

(3, 1)             (3, 3)
[[4], [5], [6]] -> [[4, 4, 4],
                    [5, 5, 5],
                    [6, 6, 6]]
'''




[[5 6 7]
 [6 7 8]
 [7 8 9]]


'\n(3, )          (1, 3)        (3, 3)\n[1, 2, 3]      [[1, 2, 3]]   [[1, 2, 3],\n                              [1, 2, 3],\n                              [1, 2, 3]]\n\n(3, 1)             (3, 3)\n[[4], [5], [6]] -> [[4, 4, 4],\n                    [5, 5, 5],\n                    [6, 6, 6]]\n'

In [ ]:
arr1 = np.array([[1, 2, 3], [1, 2, 3]]) # shape (2, 3) ndim 2
arr2 = np.array([1, 2]) # shape (2,) ndim 1
# 행, 열 개수가 다르면 브로드캐스팅 연산 불가
print(arr1 + arr2) # ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

##### 행렬 곱셈

- 점곱연산 (Dot Product / 내적)
    - 두 행렬 A, B의 곱셈은 첫 번째 행렬 A의 행과 두번째 행렬 B의 열 간의 곱셈을 수행한다. 
    - ***첫 번째 행렬 A의 열의 수*와 *두번째 행렬 B의 행의 수*가 같아야 한다.** **(중요)**
    - 연산 결과의 shape은 (첫 번재 행렬 A의 행수, 두번째 행렬 B의 열수)이다.

In [ ]:
[[1, 2],        [[5, 6],
[3, 4]]          [7, 8]]

[[1*5 + 2*7, 1*6 + 2*8],
[3*5 + 4*7, 3*6 + 4*8]]

-> 점곱 연산 결과 : [[19, 20], [43, 46]]
-> 앞에 있는 행의 수와 뒤에 있는 열의 수가 같아야 점곱 연산 가능

In [ ]:
arr1 = np.array([[1, 2],
                 [3, 4]])
arr2 = np.array([[5, 6],
                 [7, 8]])

print(arr1 * arr2, n) # 요소별 곱셈
print(" arr1.shape : ", arr1.shape, n, "arr2.shape : ", arr2.shape, n, "arr1 * arr2.shape : ", (arr1 * arr2).shape, n)

print(np.dot(arr1, arr2), n) # 행렬 곱셈
print(" np.dot(arr1, arr2).shape : ", np.dot(arr1, arr2).shape, n) # 행렬 곱셈 결과의 shape

# numpy 배열의 행렬 곱셈 .dot() 메서드 사용

[[ 5 12]
 [21 32]] 
--------------------------------

 arr1.shape :  (2, 2) 
--------------------------------
 arr2.shape :  (2, 2) 
--------------------------------
 arr1 * arr2.shape :  (2, 2) 
--------------------------------

[[19 22]
 [43 50]] 
--------------------------------

 np.dot(arr1, arr2).shape :  (2, 2) 
--------------------------------



In [ ]:
arr3 = np.array([[1, 2, 3], [4, 5, 6]]) # shape (2, 3) ndim 2
arr4 = np.array([[7, 8], [9, 10], [11, 12]]) # shape (3, 2) ndim 2

print(" arr3.shape : ", arr3.shape, n, "arr4.shape : ", arr4.shape, n, "np.dot(arr3, arr4).shape : ", np.dot(arr3, arr4).shape, n)

print(np.dot(arr3, arr4), n)

print("연산 결과의 shape은 (첫번째 행렬의 행수, 두번째 행렬의 열수)이다.")
print("내적 연산과 broadcasting 연산의 차이점, 다르다는 점을 확인하자", n)

# np.dot(arr3, arr4) -> (2, 3) * (3, 2) -> (2, 2)
# np.dot(arr4, arr3) -> (3, 2) * (2, 3) -> (3, 3)

print(np.dot(arr4, arr3), n)

 arr3.shape :  (2, 3) 
--------------------------------
 arr4.shape :  (3, 2) 
--------------------------------
 np.dot(arr3, arr4).shape :  (2, 2) 
--------------------------------

[[ 58  64]
 [139 154]] 
--------------------------------

연산 결과의 shape은 (첫번째 행렬의 행수, 두번째 행렬의 열수)이다.
내적 연산과 broadcasting 연산의 차이점, 다르다는 점을 확인하자 
--------------------------------

[[ 39  54  69]
 [ 49  68  87]
 [ 59  82 105]] 
--------------------------------



In [ ]:
# Quiz! shape으로만 결과 판단하기!

# (100, 2000) (20000, 100) : (100, 100)
# (20000, 100) (100, 20000) : (20000, 20000)
# (100, 20000) (100, 20000) : (100, 20000) -> 내적 연산 불가
# 첫 번째 행렬 A의 열의 수와 두번째 행렬 B의 행의 수가 같아야 내적 연산 가능


# 내적 연산 결과의 shape은 (첫번째 행렬의 행수, 두번째 행렬의 열수)이다.

In [75]:
# 백터 내적 연산 결과의 shape은 (1, )이다.
# 백터는 내적 연산이 되지 않는다.

arr = np.array([[1, 2, 3], [4, 5, 6]]) # shape (2, 3) ndim 2

# @ -> matmul() 연산과 같다. = dot() 연산과 같다. 내적 연산
# print(arr @ arr)
# ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

# matmul() = dot() 연산과 같다.
# (2, 3) @ (2, 3) -> (2, 3) -> 내적 연산 불가
# (3, 2) @ (2, 3) -> (3, 3) -> 내적 연산 가능

# .T
print(arr, n)
print(arr.T, n) # arr.T = arr의 전치행렬  (행-열을 교환)
print(arr @ arr.T, n) # 내적 연산 결과의 shape은 (첫번째 행렬의 행수, 두번째 행렬의 열수)이다.
# arr @ arr.T -> (2, 3) @ (3, 2) -> (2, 2) -> 내적 연산 가능

# matmul()
print(np.matmul(arr, arr.T), n)




[[1 2 3]
 [4 5 6]] 
--------------------------------

[[1 4]
 [2 5]
 [3 6]] 
--------------------------------

[[14 32]
 [32 77]] 
--------------------------------

[[14 32]
 [32 77]] 
--------------------------------



---
### 연산 함수 및 집계 함수

In [87]:
arr_negative = np.array([[-1, -2], [-100, -200]])
arr_float = np.array([[1.234, 5.678], [7.89, 10.123]])
arr = np.arange(1, 7).reshape(2, 3)

In [88]:
# 절대값
print(np.abs(arr_negative), n) # 절대값, 결과 : [[1 2], [100 200]]

# # 제곱
# np.square(arr_negative)
# np.square(arr_float)

# # 제곱근
# np.sqrt(arr_negative)
# np.sqrt(arr_float)

# # 제곱근
# np.sqrt(arr_negative)
# np.sqrt(arr_float)

[[  1   2]
 [100 200]] 
--------------------------------



In [ ]:
# 올림/ 반올림
print(np.ceil(arr_float), n)# 올림, 결과 : [[2. 6.], [8. 11.]]
print(np.round(arr_float), n) # 반올림, 결과 : [[1. 6.], [8. 10.]]
print(np.round(arr_float, 2), n) # 소수점 둘째자리에서 반올림
# 결과 : [[1.23 5.68], [7.89 10.12]]


[[ 2.  6.]
 [ 8. 11.]] 
--------------------------------

[[ 1.  5.]
 [ 7. 10.]] 
--------------------------------

[[ 1.  6.]
 [ 8. 10.]] 
--------------------------------

[[ 1.23  5.68]
 [ 7.89 10.12]] 
--------------------------------



In [ ]:
arr_float = np.array([[1.234, -5.678], [-7.89, 10.123]])

# 내림 (지정된 수보다 작은 최대 정수수)
print(np.floor(arr_float), n)

# 버림 (절삭)
print(np.trunc(arr_float), n)

[[ 1. -6.]
 [-8. 10.]] 
--------------------------------

[[ 1. -5.]
 [-7. 10.]] 
--------------------------------



In [ ]:
# 최대값 / 최소값
arr = np.array([[7, 1, 2], [8, 3, 5]])

print(arr, n) # shape (2, 3) ndim 2
print(np.max(arr), n)
print(np.min(arr), n)

print(np.max(arr, axis=0), n) # 행 단위 최대값
print(np.max(arr, axis=1), n) # 열 단위 최대값

print(np.min(arr, axis=0), n) # 행 단위 최소값
print(np.min(arr, axis=1), n) # 열 단위 최소값




[[7 1 2]
 [8 3 5]] 
--------------------------------

8 
--------------------------------

1 
--------------------------------

[8 3 5] 
--------------------------------

[7 8] 
--------------------------------

[7 1 2] 
--------------------------------

[1 3] 
--------------------------------

26 
--------------------------------

4.333333333333333 
--------------------------------

4.0 
--------------------------------



In [109]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr, n)
# 합계
print(np.sum(arr), n)
print(arr.sum(), n)

print(arr.sum(axis=0), n) # 행 단위 합계
print(arr.sum(axis=1), n) # 열 단위 합계

[[1 2 3]
 [4 5 6]] 
--------------------------------

21 
--------------------------------

21 
--------------------------------

[5 7 9] 
--------------------------------

[ 6 15] 
--------------------------------



In [112]:
print(arr)

# 평균
print(np.average(arr), n)

print(np.mean(arr), n)
print(arr.mean(), n)

print(arr.mean(axis=0), n) # 행 단위 평균
print(arr.mean(axis=1), n) # 열 단위 평균

# 중앙값
print(np.median(arr), n)

# 분산
print(np.var(arr), n)

# 표준편차
print(np.std(arr), n)

# 최대값
print(np.max(arr), n)

# 최빈값
print(np.bincount(arr), n)




[[1 2 3]
 [4 5 6]]
3.5 
--------------------------------

3.5 
--------------------------------

3.5 
--------------------------------

[2.5 3.5 4.5] 
--------------------------------

[2. 5.] 
--------------------------------

3.5 
--------------------------------

2.9166666666666665 
--------------------------------

1.707825127659933 
--------------------------------

6 
--------------------------------



ValueError: object too deep for desired array

In [115]:
# 최대값/ 최소값

arr = np.array([[1, 5, 2],
                [7, 4, 9]])

print(arr, n)
print(np.max(arr), n)
print(np.min(arr), n)
print(np.max(arr, axis=0), n) # 행 단위 최대값
print(np.max(arr, axis=1), n) # 열 단위 최대값
print(np.min(arr, axis=0), n) # 행 단위 최소값
print(np.min(arr, axis=1), n) # 열 단위 최소값

[[1 5 2]
 [7 4 9]] 
--------------------------------

9 
--------------------------------

1 
--------------------------------

[7 5 9] 
--------------------------------

[5 9] 
--------------------------------

[1 4 2] 
--------------------------------

[1 4] 
--------------------------------

