### ndarray 정렬


In [1]:
import numpy as np

In [ ]:
##### 1차원 ndarray 정렬

In [2]:
n = "\n------------------------------------------------------------------------\n"

In [81]:
arr = np.random.randint(1, 11, 10)
print(arr, n)
print(np.sort(arr), n)
print(arr)

[ 7  1  2  9  1  6  4  7 10  5] 
------------------------------------------------------------------------

[ 1  1  2  4  5  6  7  7  9 10] 
------------------------------------------------------------------------

[ 7  1  2  9  1  6  4  7 10  5]


In [84]:
# np.sort(arr) : 원본 배열을 변경하지 않고 정렬된 배열 반환

print(np.sort(arr))
arr = np.sort(arr)
print(arr, n)

[ 1  1  2  4  5  6  7  7  9 10]
[ 1  1  2  4  5  6  7  7  9 10] 
------------------------------------------------------------------------



In [85]:
print(np.sort(arr)[::-1], n)

[10  9  7  7  6  5  4  2  1  1] 
------------------------------------------------------------------------



---
##### 2차원 배열 정렬

In [113]:
arr = np.random.randint(10, size=(3, 4)) # 0 이상 10 미만의 정수 난수 생성 (3행 4열)
# 반드시 size=(행, 열) 형식으로 지정, 키워드 인자 사용해서 끝나는 인자를 지정해야 함
print(arr, n) 

[[9 0 8 4]
 [4 3 3 7]
 [9 9 1 3]] 
------------------------------------------------------------------------



In [ ]:
print(arr, n)
print(np.sort(arr), n) # 기본적으로 열 기준 정렬, axis=1
print(np.sort(arr, axis=0), n) # 행 기준 정렬 (같은 열 안에서 정렬)
print(np.sort(arr, axis=1), n) # 열 기준 정렬 (같은 행 안에서 정렬)

[[9 0 8 4]
 [4 3 3 7]
 [9 9 1 3]] 
------------------------------------------------------------------------

[[0 4 8 9]
 [3 3 4 7]
 [1 3 9 9]] 
------------------------------------------------------------------------

[[4 0 1 3]
 [9 3 3 4]
 [9 9 8 7]] 
------------------------------------------------------------------------

[[0 4 8 9]
 [3 3 4 7]
 [1 3 9 9]] 
------------------------------------------------------------------------



In [130]:
print(np.sort(arr, axis=None)) # axis=None : 축 무시 (행/열 구분없이 모든 값 정렬)
print(np.sort(arr, axis=None).shape, n)

[0 1 3 3 3 4 4 7 8 9 9 9]
(12,) 
------------------------------------------------------------------------



- np.argsort()
- 배열의 값을 정렬했을 때, 각 값의 원래 인덱스를 반환
- 정렬할 때 어떤 순서로 값을 배치해야 하는지 알려주는 인덱스를 반환
- 배열의 값을 정렬한 후, 정렬된 순서에 해당하는 인덱스를 반환환

In [ ]:
arr = np.array([100, 400, 200, 300]) # 0 : 100, 1 : 400, 2 : 200, 3 : 300
print(np.sort(arr), n)
print(np.argsort(arr), n) # 정렬된 배열의 인덱스 반환, 원본 배열의 순서 유지
print(arr[np.argsort(arr)], n) # 정렬된 배열의 인덱스 반환, 원본 배열의 순서 유지
# indices -> 팬시 인덱싱로 원본 배열 순서로 재배치

[100 200 300 400] 
------------------------------------------------------------------------

[0 2 3 1] 
------------------------------------------------------------------------

[100 200 300 400] 
------------------------------------------------------------------------



In [141]:
names = np.array(['리사', '로제', '제니', '지수'])
# 0 : 리사, 1 : 제니, 2 : 로제, 3 : 지수
album_sales = np.array([900, 870, 1000, 670])

# 두 배열을 병합하지 않고 앨범 판매량 순위 출력

print(np.sort(album_sales)[::-1], n) # 앨범 판매량 정렬
print(np.argsort(album_sales)[::-1], n) # 앨범 판매량 순위 인덱스 반환
sales_desc = np.argsort(album_sales)[::-1]

print(names[np.argsort(album_sales)[::-1]], n) # 앨범 판매량 순위 인덱스 반환
print(names[sales_desc], n)

[1000  900  870  670] 
------------------------------------------------------------------------

[2 0 1 3] 
------------------------------------------------------------------------

['제니' '리사' '로제' '지수'] 
------------------------------------------------------------------------

['제니' '리사' '로제' '지수'] 
------------------------------------------------------------------------



In [ ]:
# 2차원 배열에서 argsort() 사용
arr = np.array([[2025, 9, 8], [17, 30, 40]])
print(arr, n)
print(np.argsort(arr), n)
print(np.argsort(arr, axis=0), n) # 행 기준 정렬
print(np.argsort(arr, axis=1), n) # 열 기준 정렬
print(np.argsort(arr, axis=None), n) # 축 무시


[[2025    9    8]
 [  17   30   40]] 
------------------------------------------------------------------------

[[2 1 0]
 [0 1 2]] 
------------------------------------------------------------------------

[[1 0 0]
 [0 1 1]] 
------------------------------------------------------------------------

[[2 1 0]
 [0 1 2]] 
------------------------------------------------------------------------

[2 1 3 4 5 0] 
------------------------------------------------------------------------



IndexError: index 2 is out of bounds for axis 0 with size 2