### ndarray 병합 및 분할

In [2]:
import numpy as np

In [5]:
n= "\n-----------------------------------------------------------------------------\n"

In [ ]:
# ndarray 는 만들때 길이가 정해진다 ?
# 고정길이 배열
# 겉보기엔 추가되고 삭제가 된 것 같지만, 존재하던 ndarray는 요소가 추가된 것이 아니라,
# 새로운 배열이 생성되고 반환한다. (원본 배열은 그대로 유지된다.)

##### ndarray 요소 추가 및 삭제
- ndarray는 고정 길이 배열이므로 크기 변경이 불가하다. == 요소를 추가할 수 없다.

In [ ]:
arr = np.array([10, 20, 30])

np.append(arr, 40) # 마지막에 40 추가
np.insert(arr, 1, 15) # 원본 배열, 삽입할 위치 인덱스, 삽입할 요소소
# 1번 인덱스에 15 추가

print(arr) # 원본 배열은 그대로 유지된다.

[10 20 30]


In [5]:
arr = np.array([10, 20, 30])

arr1 = np.append(arr, 40) # 마지막에 40 추가
arr2 = np.insert(arr, 1, 15) # 원본 배열, 삽입할 위치 인덱스, 삽입할 요소소
# 1번 인덱스에 15 추가

print(arr, n)
print(arr1, n)
print(arr2, n)
print(arr2 is arr, arr2)




[10 20 30] 
-----------------------------------------------------------------------------

[10 20 30 40] 
-----------------------------------------------------------------------------

[10 15 20 30] 
-----------------------------------------------------------------------------

False [10 15 20 30]


In [ ]:
# append
arr = np.arange(1,13).reshape(3, 4) # ndim = 2 # reshape() 요소의 개수가 같아야 한다.
print(arr ,n)
print(np.append(arr, 40), n) # 차원 축소, 왜냐하면 1차원 배열로 반환되기 때문이다.
print(np.append(arr, [[5, 6, 7, 8]]), n) # 2차원 배열 추가
print(np.append(arr, [[15, 16, 17, 18]], axis=0), n) # 2차원 배열 추가
print(np.append(arr, [[55], [66], [77]], axis=1), n) # 2차원 형태로 추가가

# concatenate : 배열 병합

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 
-----------------------------------------------------------------------------

[ 1  2  3  4  5  6  7  8  9 10 11 12 40] 
-----------------------------------------------------------------------------

[ 1  2  3  4  5  6  7  8  9 10 11 12  5  6  7  8] 
-----------------------------------------------------------------------------

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [15 16 17 18]] 
-----------------------------------------------------------------------------

[[ 1  2  3  4 55]
 [ 5  6  7  8 66]
 [ 9 10 11 12 77]] 
-----------------------------------------------------------------------------



In [37]:
# 2차원 배열에서 insert()
arr = np.arange(1,13).reshape(3, 4) # ndim = 2 # reshape() 요소의 개수가 같아야 한다.
print(arr ,n)
print(np.insert(arr, 1, 100), n) # 차원 축소 # axis=None : 1차원 배열로 반환
print(np.insert(arr, 1, 100, axis=0), n) # 2차원 배열 추가
print(np.insert(arr, 1, [100, 200, 300, 400], axis=0), n) # 2차원 배열 추가
print(np.insert(arr, 1, 100, axis=1), n) # 2차원 배열 추가
print(np.insert(arr, 1, [222], axis=1), n) # 2차원 배열 추가
# 원본 배열, 삽입할 위치 인덱스, 삽입할 요소, axis (axis=0 : 행 추가, axis=1 : 열 추가)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 
-----------------------------------------------------------------------------

[  1 100   2   3   4   5   6   7   8   9  10  11  12] 
-----------------------------------------------------------------------------

[[  1   2   3   4]
 [100 100 100 100]
 [  5   6   7   8]
 [  9  10  11  12]] 
-----------------------------------------------------------------------------

[[  1   2   3   4]
 [100 200 300 400]
 [  5   6   7   8]
 [  9  10  11  12]] 
-----------------------------------------------------------------------------

[[  1 100   2   3   4]
 [  5 100   6   7   8]
 [  9 100  10  11  12]] 
-----------------------------------------------------------------------------

[[  1 222   2   3   4]
 [  5 222   6   7   8]
 [  9 222  10  11  12]] 
-----------------------------------------------------------------------------



In [39]:
# np.delete()
arr = np.arange(1,15)
print(arr, n)
print(np.delete(arr, 7), n) # 7번째 요소 삭제
print(arr, n)
print(np.delete(arr, [1, 3, 5]), n) # 1, 3, 5번째 요소 삭제

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14] 
-----------------------------------------------------------------------------

[ 1  2  3  4  5  6  7  9 10 11 12 13 14] 
-----------------------------------------------------------------------------

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14] 
-----------------------------------------------------------------------------

[ 1  3  5  7  8  9 10 11 12 13 14] 
-----------------------------------------------------------------------------



In [43]:
# 2차원 배열에서 delete()
arr = np.arange(1,13).reshape(3, 4)
print(arr, n)

print(np.delete(arr, 1), n) # 1차원으로 flatten 되어 삭제
print(np.delete(arr, 1, axis=0), n) # 행 삭제
print(np.delete(arr, 1, axis=1), n) # 열 삭제

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 
-----------------------------------------------------------------------------

[ 1  3  4  5  6  7  8  9 10 11 12] 
-----------------------------------------------------------------------------

[[ 1  2  3  4]
 [ 9 10 11 12]] 
-----------------------------------------------------------------------------

[[ 1  3  4]
 [ 5  7  8]
 [ 9 11 12]] 
-----------------------------------------------------------------------------



---
##### ndarray 병합

- np.append()
- np.vstack()
- np.hstack()
- np.concatenate()

In [53]:
arr1 = np.arange(1, 13).reshape(3, 4)
arr2 = np.arange(13, 25).reshape(3, 4)
print(arr1, n , arr2, n)

print(np.append(arr1, arr2), n) # 1차원 배열로 변환 후 추가, flatten 되어 추가
print(np.append(arr1, arr2, axis=0), n) # 행 추가 병합
print(np.append(arr1, arr2, axis=1), n) # 열 추가 병합

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 
-----------------------------------------------------------------------------
 [[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]] 
-----------------------------------------------------------------------------

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24] 
-----------------------------------------------------------------------------

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]] 
-----------------------------------------------------------------------------

[[ 1  2  3  4 13 14 15 16]
 [ 5  6  7  8 17 18 19 20]
 [ 9 10 11 12 21 22 23 24]] 
-----------------------------------------------------------------------------



In [56]:
# np.vstack() : axis=0 행 추가 병합
# 병합 대상 ndarray를 튜플/리스트로 묶어서 전달해야 한다.
print(np.vstack((arr1, arr2)), n)

# np.hstack() : axis=1 열 추가 병합
# 병합 대상 ndarray를 튜플/리스트로 묶어서 전달해야 한다.
print(np.hstack([arr1, arr2]), n)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]] 
-----------------------------------------------------------------------------

[[ 1  2  3  4 13 14 15 16]
 [ 5  6  7  8 17 18 19 20]
 [ 9 10 11 12 21 22 23 24]] 
-----------------------------------------------------------------------------



In [60]:
# np.concatenate() : axis=0 행 추가 병합
print(arr1, n, arr2, n)

print(np.concatenate((arr1, arr2)), n)
print(np.concatenate((arr1, arr2), axis=0), n)

# np.concatenate() : axis=1 열 추가 병합
print(np.concatenate((arr1, arr2), axis=1), n)
print(np.concatenate((arr1, arr2), axis=None), n)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 
-----------------------------------------------------------------------------
 [[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]] 
-----------------------------------------------------------------------------

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]] 
-----------------------------------------------------------------------------

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]] 
-----------------------------------------------------------------------------

[[ 1  2  3  4 13 14 15 16]
 [ 5  6  7  8 17 18 19 20]
 [ 9 10 11 12 21 22 23 24]] 
-----------------------------------------------------------------------------

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24] 
-----------------------------------------------------------------------------



---
##### ndarray 분할

- np.split() # 원본배열, 분할할 갯수수

In [ ]:
arr = np.concatenate((arr1, arr2))
print(arr, n) # shape(6, 4)

# 약수를 사용해 분할할 갯수를 정해야 한다.
print(np.split(arr, 2), n) # 원본배열, 분할할 갯수, axis
print(np.split(arr, 3, axis=0), n) # 행 분할
print(np.split(arr, 2, axis=1), n) # 열 분할

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]] 
-----------------------------------------------------------------------------

[array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]]), array([[13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])] 
-----------------------------------------------------------------------------

[array([[1, 2, 3, 4],
       [5, 6, 7, 8]]), array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]]), array([[17, 18, 19, 20],
       [21, 22, 23, 24]])] 
-----------------------------------------------------------------------------

[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18],
       [21, 22]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12],
       [15, 16],
       [19, 20],
       [23, 24]])] 
-----------------------------------------------------------------------------



In [77]:
num = 2
print(np.split(arr, num, axis=0), n) # 6행: 1, 2, 3, 6
print(np.split(arr, num, axis=1), n) # 4열: 1, 2, 4
# num = 3, 'array split does not result in an equal division'

[array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]]), array([[13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])] 
-----------------------------------------------------------------------------

[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18],
       [21, 22]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12],
       [15, 16],
       [19, 20],
       [23, 24]])] 
-----------------------------------------------------------------------------



In [72]:

# np.vsplit() : 행 분할
print(np.vsplit(arr, 6), n)
# np.hsplit() : 열 분할
print(np.hsplit(arr, 2), n)

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]]), array([[13, 14, 15, 16]]), array([[17, 18, 19, 20]]), array([[21, 22, 23, 24]])] 
-----------------------------------------------------------------------------

[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18],
       [21, 22]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12],
       [15, 16],
       [19, 20],
       [23, 24]])] 
-----------------------------------------------------------------------------

