### ndarray 병합 및 분할

In [1]:
import numpy as np

In [2]:
n= "\n-----------------------------------------------------------------------------\n"

In [ ]:
# ndarray 는 만들때 길이가 정해진다 ?
# 고정길이 배열
# 겉보기엔 추가되고 삭제가 된 것 같지만, 존재하던 ndarray는 요소가 추가된 것이 아니라,
# 새로운 배열이 생성되고 반환한다. (원본 배열은 그대로 유지된다.)

##### ndarray 요소 추가 및 삭제
- ndarray는 고정 길이 배열이므로 크기 변경이 불가하다. == 요소를 추가할 수 없다.

In [ ]:
arr = np.array([10, 20, 30])

np.append(arr, 40) # 마지막에 40 추가
np.insert(arr, 1, 15) # 원본 배열, 삽입할 위치 인덱스, 삽입할 요소소
# 1번 인덱스에 15 추가

print(arr) # 원본 배열은 그대로 유지된다.

[10 20 30]


In [5]:
arr = np.array([10, 20, 30])

arr1 = np.append(arr, 40) # 마지막에 40 추가
arr2 = np.insert(arr, 1, 15) # 원본 배열, 삽입할 위치 인덱스, 삽입할 요소소
# 1번 인덱스에 15 추가

print(arr, n)
print(arr1, n)
print(arr2, n)
print(arr2 is arr, arr2)




[10 20 30] 
-----------------------------------------------------------------------------

[10 20 30 40] 
-----------------------------------------------------------------------------

[10 15 20 30] 
-----------------------------------------------------------------------------

False [10 15 20 30]
