---
### ndarray 형태 변경

In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [5]:
n= "\n-----------------------------------------------------------------------------\n"

In [17]:
# reshape() : 배열의 형태 변경
# 원본 배열의 요소 개수와 다르면 오류 발생
# 원본 요소의 갯수가 맞는 경우 차원 변경 가능

arr = np.arange(12)
print(arr.ndim, arr.shape, n)
print(arr, n) # shape(12,) # 1차원 배열

arr1 = arr.reshape(3, 4)
arr2 = arr.reshape(6, 2)
arr3 = arr.reshape(1, 12) # 2차원 배열로 변경
# arr3 = arr.reshape(2, 7) # 2차원 배열로 변경, 원본 배열의 요소 개수와 다르면 오류 발생
arr4 = arr.reshape(2, 3, 2) # 3차원 배열로 변경
# arr5 = arr.reshape(2, 2, 1) # 원본 배열의 요소 개수와 다르면 오류 발생
print(arr1, n, arr1.ndim, arr1.shape, n)
print(arr2, n, arr2.ndim, arr2.shape, n)
print(arr3, n, arr3.ndim, arr3.shape, n)
print(arr4, n, arr4.ndim, arr4.shape, n)
print(arr, n)

1 (12,) 
-----------------------------------------------------------------------------

[ 0  1  2  3  4  5  6  7  8  9 10 11] 
-----------------------------------------------------------------------------

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 
-----------------------------------------------------------------------------
 2 (3, 4) 
-----------------------------------------------------------------------------

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]] 
-----------------------------------------------------------------------------
 2 (6, 2) 
-----------------------------------------------------------------------------

[[ 0  1  2  3  4  5  6  7  8  9 10 11]] 
-----------------------------------------------------------------------------
 2 (1, 12) 
-----------------------------------------------------------------------------

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]] 
-----------------------------------------------------------------------------
 3

In [ ]:
# reshape() -> -1
arr = np.arange(12)
arr1 = arr.reshape(-1) # 1차원 배열로 변경
print(arr, n, arr.ndim, arr.shape, n)
print(arr1, n, arr1.ndim, arr1.shape, n)

# -1인 축은 자동 계산
arr2 = arr.reshape(3, -1) # 3행으로 변경, 열의 개수는 자동으로 계산
arr3 = arr.reshape(-1, 3) # 3열로 변경, 행의 개수는 자동으로 계산

print(arr1, n, arr1.ndim, arr1.shape, n)
print(arr2, n, arr2.ndim, arr2.shape, n)
print(arr3, n, arr3.ndim, arr3.shape, n)

[ 0  1  2  3  4  5  6  7  8  9 10 11] 
-----------------------------------------------------------------------------
 1 (12,) 
-----------------------------------------------------------------------------

[ 0  1  2  3  4  5  6  7  8  9 10 11] 
-----------------------------------------------------------------------------
 1 (12,) 
-----------------------------------------------------------------------------

[ 0  1  2  3  4  5  6  7  8  9 10 11] 
-----------------------------------------------------------------------------
 1 (12,) 
-----------------------------------------------------------------------------

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 
-----------------------------------------------------------------------------
 2 (3, 4) 
-----------------------------------------------------------------------------

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]] 
-----------------------------------------------------------------------------
 2 (4, 3) 
----------------------------

In [ ]:
# np.ravel() : 배열을 1차원으로 변경 reshape(-1)과 동일
arr = np.arange(50).reshape(5, 10)
print(arr, n, arr.ndim, arr.shape, n)
arr1 = arr.ravel()
print(arr1, n, arr1.ndim, arr1.shape, n)
# np.flatten() : 배열을 1차원으로 변경
arr2 = arr.flatten()
print(arr2, n, arr2.ndim, arr2.shape, n)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]] 
-----------------------------------------------------------------------------
 2 (5, 10) 
-----------------------------------------------------------------------------

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49] 
-----------------------------------------------------------------------------
 1 (50,) 
-----------------------------------------------------------------------------

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49] 
-----------------------------------------------------------------------------
 1 (50,) 
-----------------------------------------------------------------------------



In [34]:
# np.expand_dims() : 배열을 차원 추가
arr1d = np.arange(10)
print(arr1d, n, arr1d.ndim, arr1d.shape, n)
arr2d = np.expand_dims(arr1d, axis=0)
print(arr2d, n, arr2d.ndim, arr2d.shape, n)
arr3d = np.expand_dims(arr1d, axis=1)
print(arr3d, n, arr3d.ndim, arr3d.shape, n)
# arr4d = np.expand_dims(arr1d, axis=2) # axis 2 is out of bounds for array of dimension 2
# print(arr4d, n, arr4d.ndim, arr4d.shape, n)



[0 1 2 3 4 5 6 7 8 9] 
-----------------------------------------------------------------------------
 1 (10,) 
-----------------------------------------------------------------------------

[[0 1 2 3 4 5 6 7 8 9]] 
-----------------------------------------------------------------------------
 2 (1, 10) 
-----------------------------------------------------------------------------

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]] 
-----------------------------------------------------------------------------
 2 (10, 1) 
-----------------------------------------------------------------------------



In [36]:
arr2d = np.arange(10).reshape(2, 5)
print(arr2d, n, arr2d.ndim, arr2d.shape, n)
arr2d1 = np.expand_dims(arr2d, axis=0)
print(arr2d1, n, arr2d1.ndim, arr2d1.shape, n)
arr2d2 = np.expand_dims(arr2d, axis=1)
print(arr2d2, n, arr2d2.ndim, arr2d2.shape, n)
arr2d3 = np.expand_dims(arr2d, axis=2)
print(arr2d3, n, arr2d3.ndim, arr2d3.shape, n)

[[0 1 2 3 4]
 [5 6 7 8 9]] 
-----------------------------------------------------------------------------
 2 (2, 5) 
-----------------------------------------------------------------------------

[[[0 1 2 3 4]
  [5 6 7 8 9]]] 
-----------------------------------------------------------------------------
 3 (1, 2, 5) 
-----------------------------------------------------------------------------

[[[0 1 2 3 4]]

 [[5 6 7 8 9]]] 
-----------------------------------------------------------------------------
 3 (2, 1, 5) 
-----------------------------------------------------------------------------

[[[0]
  [1]
  [2]
  [3]
  [4]]

 [[5]
  [6]
  [7]
  [8]
  [9]]] 
-----------------------------------------------------------------------------
 3 (2, 5, 1) 
-----------------------------------------------------------------------------



In [40]:
# np.squeeze() : 차원의 값(= 해당 차원의 요소 개수)이 1인 경우 차원 제거
arr = np.array([[1, 2]])
print(arr, n, arr.ndim, arr.shape, n)
arr1 = np.squeeze(arr)
print(arr1, n, arr1.ndim, arr1.shape, n)
arr2 = np.squeeze(arr, axis=0)
print(arr2, n, arr2.ndim, arr2.shape, n)
arr3 = np.squeeze(arr, axis=1)
print(arr3, n, arr3.ndim, arr3.shape, n)

# np.transpose() : 배열을 전치
# np.rollaxis() : 배열을 축 순서 변경
# np.swapaxes() : 배열을 축 순서 변경

[[1 2]] 
-----------------------------------------------------------------------------
 2 (1, 2) 
-----------------------------------------------------------------------------

[1 2] 
-----------------------------------------------------------------------------
 1 (2,) 
-----------------------------------------------------------------------------

[1 2] 
-----------------------------------------------------------------------------
 1 (2,) 
-----------------------------------------------------------------------------



ValueError: cannot select an axis to squeeze out which has size not equal to one